### PR TITLE
data: project addition by abhay-raj19  #536

### PR DESCRIPTION
**Pull request by abhay-raj19**
## Related Issue

Issue Number: #536 

## Description
Added up a simple project that is of Drum kit .

## Screenshots
image

Project descriptive page :
image

### CODE REVIEW

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Comment by abhay-raj19** [comment]
hey @priyankarpal how to rectify these quality check  and specifically format lock is falling .

**Comment by abhay-raj19** [comment]
my one format lock test was not passed why so @priyankarpal

**Comment by priyankarpal** [comment]
You can ignore this error I removed this gh action

**Pull request merged**
