### PR TITLE
chore: added sahil chalke to projects #1729

### PR DESCRIPTION
**Pull request by Sahilll15**
## Related Issue
#1729

### CODE REVIEW

**Review by priyankarpal — CHANGES_REQUESTED** [review]
add issue number

**Review by priyankarpal — CHANGES_REQUESTED** [review]
@Sahilll15 you've added the PR number. You need to add the issue number after that I can merge.

**Comment by Sahilll15** [comment]
@priyankarpal  done

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Pull request merged**
