### PR TITLE
Added Projects Successfully

### PR DESCRIPTION
**Pull request by Harshu467**
## Description

Added 5 Projects

## Screenshots
image

## Checklist for projects addition 
 
- [x ] My project has contribution guidelines.
- [ x] My project has a Code of Conduct.
- [ x] My project has a README file.
- [x ] My project has a License.

---

Please note that if your project doesn't meet these requirements, your PR may be closed. Make sure to include these elements in your project before submitting the PR.

### CODE REVIEW

**Comment by Harshu467** [comment]
@priyankarpal Added Projects , Check and merge with issue number #1384

**Comment by priyankarpal** [comment]
> @priyankarpal Added Projects , Check and merge with issue number #1384

this is the PR number, please add the issue number.

**Review by priyankarpal — CHANGES_REQUESTED** [review]
In order to merge the pull request, it is essential that your projects include a contributing guide, code of conduct, license, and a readme. These requirements must be fulfilled without any exceptions.

**Comment by Harshu467** [comment]
I have created new PR with proper guidelines, Closing this PR

**Pull request closed without merging**
