### PR TITLE
feat: add quality check github action #304

### PR DESCRIPTION
**Pull request by Syed-Ali-Abbas-Zaidi**
## Description

This PR adds Quality Check github action.

## Checklist

Please review and check off the following items before submitting your PR:

 

- [x] I have tested my changes to ensure they work as expected
- [ ] I have included documentation for any new features or changes
- [x] I have formatted my code according to the project's style guidelines
- [ ] I have written tests for any new features or changes
- [x] I have run the project's test suite and verified that all tests pass
- [ ] I have updated the README and any other relevant documentation
- [x] I have checked for any spelling or grammatical errors

### CODE REVIEW

**Comment by priyankarpal** [comment]
it's falling because package-lock,json is not formatted

**Comment by priyankarpal** [comment]
what if we use `pnpm prettier --write .` instead of `pnpm prettier --write pnpm-lock.yaml` to format all files?

**Comment by Syed-Ali-Abbas-Zaidi** [comment]
> what if we use `pnpm prettier --write .` instead of `pnpm prettier --write pnpm-lock.yaml` to format all files?

Then this quality check will always pass, even if the PR contains formatting errors in other files due to `--write .` it will format all files, and `pnpm lint` will always pass no matter what.

**Comment by priyankarpal** [comment]
> > what if we use `pnpm prettier --write .` instead of `pnpm prettier --write pnpm-lock.yaml` to format all files?
> 
> Then this quality check will always pass, even if the PR contains formatting errors in other files due to `--write .` it will format all files, and `pnpm lint` will always pass no matter what.

ok

**Comment by priyankarpal** [comment]
so finally it's all done?

**Comment by Syed-Ali-Abbas-Zaidi** [comment]
> so finally it's all done?

Yes, Ready to Merge!

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Pull request merged**
