### PR TITLE
chore: setup husky + eslint extends with prettier

### PR DESCRIPTION
**Pull request by balaji-sivasakthi**
### Related issue:-
#1824 
### Changes Made:-
- setup eslint and prettier
- setup pre-commit hook (styling and lint-stage)
- setup commit-msg hook (accept valid git commit message)

### CODE REVIEW

**Comment by priyankarpal** [comment]
let me check & will give you update soon

**Review by priyankarpal — CHANGES_REQUESTED** [review]
@balaji-sivasakthi I just checked your branch but your branch is not updated. we are using NetJs & typescript. please look into it

**Comment by balaji-sivasakthi** [comment]
@priyankarpal I've fixed the build issue in the local environment. However, you need to take a look at what happens in the production environment. Please let me know ASAP.

**Comment by balaji-sivasakthi** [comment]
I pulled from the **upstream main**, and then I made some changes. It's not a matter of the main branch here. I raised a PR from my new branch `husky-implementation`; kindly check that one, as it is up to date.

**Comment by balaji-sivasakthi** [comment]
@priyankarpal  I think you should check the Vercel build log. It will help to resolve this issue.

**Comment by balaji-sivasakthi** [comment]
project hut

**Comment by balaji-sivasakthi** [comment]
next

**Comment by balaji-sivasakthi** [comment]
build

**Comment by priyankarpal** [comment]
@balaji-sivasakthi we are using `pnpm` so please use `pnpm`. avoid to use `npm`.

image

**Comment by balaji-sivasakthi** [comment]
Thank you for providing the information. I will work on resolving the issue promptly..

**Comment by balaji-sivasakthi** [comment]
@priyankarpal Check now!

**Comment by priyankarpal** [comment]
> @priyankarpal Check now 🎉

yeah sure will check soon.

**Comment by priyankarpal** [comment]
@balaji-sivasakthi I think we don't need to use `prepare.js` when we will do `pnpm i` it will install all dependencies.

**Comment by balaji-sivasakthi** [comment]
> @balaji-sivasakthi I think we don't need to use `prepare.js` when we will do `pnpm i` it will install all dependencies.  

There is an edge case for Husky:

`hint: The '.husky/pre-commit' hook was ignored because it's not set as executable. hint: You can disable this warning with `git config advice.ignoredHook false`. hint: The '.husky/commit-msg' hook was ignored because it's not set as executable. hint: You can disable this warning with `git config advice.ignoredHook false`.`

if someone uses macOS/Linux, it requires permission to install Husky on their system. So, I have written a script to handle installing Husky when using `pnpm install` for the first time.

**Comment by priyankarpal** [comment]
> > @balaji-sivasakthi I think we don't need to use `prepare.js` when we will do `pnpm i` it will install all dependencies.
> 
> @priyankarpal
> 
> There is an edge case for Husky:
> 
> ```
> husky - Git hooks installed
> chmod: .husky/*: No such file or directory # I have .husky folder. Testing your branch only
> Setting permissions failed
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```
> 
> if someone uses macOS/Linux, it requires permission to install Husky on their system. So, I have written a script to handle installing Husky when using `pnpm install` for the first time.

ok but I'm using Linux. please check the above commitlink site where you can see the whole setup. we don't need to add extra code

**Comment by balaji-sivasakthi** [comment]
Should I remove it?

**Comment by priyankarpal** [comment]
> Should I remove it?

yeah

**Comment by balaji-sivasakthi** [comment]
@priyankarpal Sure, I will do it.

**Comment by balaji-sivasakthi** [comment]
@priyankarpal Check now

**Review by priyankarpal — CHANGES_REQUESTED** [review]
@balaji-sivasakthi currently you don't need to write all code for `husky` + `commitlint` setup 
delete all previous setup
Just follow the steps.
```
1. pnpm install --save-dev @commitlint/{cli,config-conventional}
2. echo "module.exports = { extends: ['@commitlint/config-conventional'] };" > commitlint.config.js
3. pnpm install husky --save-dev
4. pnpx husky install
5. pnpx husky add .husky/commit-msg  'npx --no -- commitlint --edit ${1}'
```

**Comment by balaji-sivasakthi** [comment]
> * setup eslint and prettier

@priyankarpal  What about this ? Is this ok?

**Comment by priyankarpal** [comment]
> > * setup eslint and prettier
> 
> @priyankarpal What about this? Is this ok? or should I remove it?

eslint already is here & for now we need to skip prettier

**Pull request closed without merging**
