### PR TITLE
 chore: project addition by srujana-16 #1406 

### PR DESCRIPTION
**Pull request by srujana-16**
## Related Issue

Solves #1406 

## Description

I have added a new project of mine. This repository contains games built using different tech stacks: web development with HTML, CSS, and JavaScript, and terminal games in Python.

## Screenshots

screenshot

## Checklist for projects addition 
 
- [x] My project has contribution guidelines.
- [x] My project has a Code of Conduct.
- [x] My project has a README file.
- [x] My project has a License.

---

Please note that if your project doesn't meet these requirements, your PR may be closed. Make sure to include these elements in your project before submitting the PR.

### CODE REVIEW

**Review by priyankarpal — CHANGES_REQUESTED** [review]
this branch has conflicts error please resolve & make sure that your project has valid contributing guide & code of conduct

**Comment by srujana-16** [comment]
I have made the changes, please check

**Comment by priyankarpal** [comment]
> I have made the changes, please check

now I'm merging this PR please add contributing guide & code of conduct in your projects

**Review by priyankarpal — APPROVED** [review]

**Comment by srujana-16** [comment]
I have added them.

**Pull request merged**
