### PR TITLE
Changed from Hashrouter to BrowserRouter

### PR DESCRIPTION
**Pull request by JasonDsouza212**
### Due to the unnecessary **#** symbol in the website navigation caused by **HashRouter**, it has been replaced with **BrowserRouter** to resolve the issue.

#102

### CODE REVIEW

**Comment by JasonDsouza212** [comment]
is it ,It works fine in local environment

**Comment by priyankarpal** [comment]
> is it ,It works fine in local environment

yes it's working fine also in my local but after deploying 404 😢

**Comment by priyankarpal** [comment]
still error.

image

**Comment by priyankarpal** [comment]
😢

**Comment by priyankarpal** [comment]
We need to use a dynamic route

**Comment by JasonDsouza212** [comment]
ok Ill try that

**Comment by priyankarpal** [comment]
So I'm closing this PR Create a new one

**Pull request closed without merging**
