### PR TITLE
chore: project addition by aakanksha

### PR DESCRIPTION
**Pull request by devWonderkind**
## Related Issue
#1360 

## Description
It's a logo-finding website. Here you can enter any website URL and find the logo of the website and download the logo.

## Screenshots
save

## Checklist for projects addition 
 
-  [x] My project has contribution guidelines.
- [x] My project has a Code of Conduct.
- [x] My project has a README file.
- [x] My project has a License.

---

Please note that if your project doesn't meet these requirements, your PR may be closed. Make sure to include these elements in your project before submitting the PR.

### CODE REVIEW

**Review by priyankarpal — CHANGES_REQUESTED** [review]
please add a valid github repo url

**Review by priyankarpal — CHANGES_REQUESTED** [review]
In order to merge the pull request, it is essential that your projects include a valid contributing guide, code of conduct, license, and a readme. These requirements must be fulfilled without any exceptions.

**Comment by devWonderkind** [comment]
All required changes have been done now.
thanks @priyankarpal

**Comment by priyankarpal** [comment]
this branch has a conflicts error. Please resolve it

**Comment by priyankarpal** [comment]
> this branch has a conflicts error. Please resolve it

resolved

**Pull request merged**
