### PR TITLE
Fix issue 715

### PR DESCRIPTION
**Pull request by Bhanuteja01**
## Related Issue
#715

## Description
changed the colour of the scrolll to top button

## Screenshots
Screenshot (5)

Screenshot (6)

### CODE REVIEW

**Review by Bhanuteja01 — COMMENTED** [review]
changed the colour of the scroll to top button

**Comment by priyankarpal** [comment]
https://github.com/priyankarpal/ProjectsHut/assets/88102392/2c0c848d-dd5a-48ed-adc5-b9c6a55048aa

**Comment by Bhanuteja01** [comment]
should i increase intensity of the colour

**Comment by priyankarpal** [comment]
> should i increase intensity of the colour

yes

**Comment by Bhanuteja01** [comment]
ok

**Pull request closed without merging**
