### PR TITLE
Revert "Query resolved"

### PR DESCRIPTION
**Pull request by priyankarpal**
Reverts priyankarpal/ProjectsHut#29

### CODE REVIEW

**Comment by ujjawaltyagii** [comment]
Changes were reverted ! was there any issue ??

**Comment by priyankarpal** [comment]
> Changes were reverted! was there any issue ??

Yes. I there some problems 
Screenshot from 2023-02-21 23-19-38

**Comment by ujjawaltyagii** [comment]
ooh !! found the issue ! everything was working fine on my system so i  didn't notice !(issue came during  resolving MERGE CONFLICT)

**Comment by priyankarpal** [comment]
> ooh !! found the issue ! everything was working fine on my system so i didn't notice !(issue came during resolving MERGE CONFLICT)

ohhh just create another one.

**Pull request merged**
