### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by NaimCode**
## Description

I added french translation for READme, Code of conduct and contributing files.

## Related Issue

#283 

## Checklist

Please review and check off the following items before submitting your PR:

 

- [x] I have tested my changes to ensure they work as expected
- [x] I have run the project's test suite and verified that all tests pass
- [x] I have checked for any spelling or grammatical errors

### CODE REVIEW

**Comment by priyankarpal** [comment]
format these files

translations/French/CODE_OF_CONDUCT.md
translations/French/contributing.md
translations/French/README.md


use `pnpm format` to format files & commit

**Review by Deva-1903 — APPROVED** [review]
Great effort👏 Thanks for the contribution

**Comment by priyankarpal** [comment]
> Great effortclap Thanks for the contribution

Thank you for approving this PR. but @Deva-1903 please check the test cases. There are some formatting errors if we merge it, it will create another error later.

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Comment by Deva-1903** [comment]
> > Great effortclap Thanks for the contribution
> 
> Thank you for approving this PR. but @Deva-1903 please check the test cases. There are some formatting errors if we merge it, it will create another error later.

Because you mentioned them earlier, I didn't want to bring them up again.

**Comment by NaimCode** [comment]
Thank You guys, and sorry it took me 4 days.

**Pull request merged**
