### PR TITLE
Refactor to Change the Router

### LINKED ISSUE #494: [Feat]: Change the Router to use Data APIs
### What feature?

We can change the Router from Router to RouterProvider so that we can use various features of the data API such as loader and actions.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by kailashchoudhary11**
fixes #494

### CODE REVIEW

**Comment by priyankarpal** [comment]
broked 

https://github.com/priyankarpal/ProjectsHut/assets/88102392/9e68e465-1be9-46f7-b06d-b8dc2107da7b

**Comment by kailashchoudhary11** [comment]
Fixed.

**Comment by kailashchoudhary11** [comment]
> loading page not showing

Yeah because there is no delay in loading. It will be only visible when we are fetching data from remote APIs since in that case it may take some time to fetch the data.

**Comment by priyankarpal** [comment]
> > loading page not showing
> 
> Yeah because there is no delay in loading. It will be only visible when we are fetching data from remote APIs since in that case it may take some time to fetch the data.

I mean splash screen is not showing


https://github.com/priyankarpal/ProjectsHut/assets/88102392/045a6cba-7bef-4152-8243-6542644208ea

**Comment by kailashchoudhary11** [comment]
I've added it, but it is not required.

**Comment by priyankarpal** [comment]
wait leat me check whole code after that I can merge

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Pull request merged**
