### PR TITLE
fix: Improved Project Input Background #1028

### PR DESCRIPTION
**Pull request by jibola2588**
## Related Issue

The input background was changed from white to transparent and a focus effect was added to the input element #1028 

## Description

Add focus to project input, remove the background color

Ensure focus functionality on input, and improve the visual appearance

### CODE REVIEW

**Review by priyankarpal — CHANGES_REQUESTED** [review]
- this branch has a conflicts error. Please resolve it
- add a good PR title

**Comment by jibola2588** [comment]
done sir

**Comment by priyankarpal** [comment]
> done sir

why deployment is failing?

**Comment by jibola2588** [comment]
> > done sir
> 
> why deployment is failing?

sir,I do not know why the deployment is failing, I can't access the deployment logs because I don't have login access

**Comment by priyankarpal** [comment]
> > > done sir
> > 
> > 
> > why deployment is failing?
> 
> sir, I do not know why the deployment is failing, I can't access the deployment logs because I don't have login access

there is a problem with the package.json update the file using `pnpm upgrade --latest` & remove hover bg-white

**Pull request closed without merging**
