### PR TITLE
Dark and Light Theme

### PR DESCRIPTION
**Pull request by Saurav-Pant**

### CODE REVIEW

**Comment by priyankarpal** [comment]
could you solve this error?

image

**Comment by priyankarpal** [comment]
there are some problems try to fix it 😢

**Comment by Saurav-Pant** [comment]
> there are some problems try to fix it 😢
Yes, i am trying but in my browser, it is running, not showing any errors

**Comment by priyankarpal** [comment]
> > there are some problems try to fix it cry
> > Yes, i am trying but in my browser, it is running, not showing any errors

take your time to find the errors. also, one suggestion for you, whenever you create PR/issue to any repo, try to add a good & clear title & description

**Comment by Saurav-Pant** [comment]
> > > there are some problems try to fix it cry
> > > Yes, i am trying but in my browser, it is running, not showing any errors
> 
> take your time to find the errors. also, one suggestion for you, whenever you create PR/issue to any repo, try to add a good & clear title & description

ok, Thanks for the suggestion, I will keep it in mind next Time.

**Comment by Saurav-Pant** [comment]
I think this error will not solve by me, sorry for that, please assign it to anyone else, and I will work on any different issue.

**Comment by priyankarpal** [comment]
> I think this error will not solve by me, sorry for that, please assign it to anyone else, and I will work on any different issue.

ok so I'm closing this error. I will work on it later

**Pull request closed without merging**
