### PR TITLE
Sonustar patch 4

### PR DESCRIPTION
**Pull request by sonustar**
## Related Issue

Issue #462
## Description

adding my project and updating the JSON file.

## Screenshots

Screenshot 2023-05-21 132355

### CODE REVIEW

**Comment by sonustar** [comment]
please sir accept and merge my pull request

**Comment by priyankarpal** [comment]
please solve the conflict error.

**Comment by sonustar** [comment]
hello sir, I have resolved the conflict which was created in the JSON file @priyankarpal

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Pull request merged**
