### PR TITLE
Changed the background colors in the dark and light mode

### LINKED ISSUE #724: [style]: The background color in the dark mode can be enhanced from simple black to some different color gradient
### What's the style idea?

# Aim

- The idea is that when dark mode is enabled simple black color appears. We could change that background color to some different color gradient which would look more beautiful. 

Please assign me this issue under GSSoC-2023

### Add screenshots

Capture

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by parag477**
## Related Issue

Closes #724 

## Description

I have added different colors other than simple black and white in the dark and light modes respectively. This will make the website look more beautify. Hope you like this little contribution from my side.

## Screenshots

Capture2

Capture1

### CODE REVIEW

**Comment by priyankarpal** [comment]
ig previous one is good

**Comment by parag477** [comment]
are you talking about both the themes or a specific one?

**Comment by priyankarpal** [comment]
> are you talking about both the themes or a specific one?

black

**Comment by priyankarpal** [comment]
ig we don't change the bg color so I'm closing this PR

**Pull request closed without merging**
