### PR TITLE
added-c-project

### LINKED ISSUE #428: adding my C projects to website
Hi! I would like to add my C projects to the website. 
"I'm in GSSOC'23"

### PR DESCRIPTION
**Pull request by akkshayTandon**
## Related Issue

closes #428 

## Description

added my C programs

## Screenshots

nil

### CODE REVIEW

**Comment by priyankarpal** [comment]
please add your projects here you can check the docs for more information

**Comment by akkshayTandon** [comment]
Why does every time quality check keeps failing, even after the `pnpm format` command?

**Comment by priyankarpal** [comment]
> Why does every time quality check keeps failing, even after the `pnpm format` command?

yes

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Pull request merged**
