### PR TITLE
Creating a footer for our project

### PR DESCRIPTION
**Pull request by Bharadwajshivam28**
I have created a Footer for our project also by giving Discord and GitHub button. @priyankarpal 

Footer scree

Screenshot from 2023-04-23 11-33-31
nshot:

issue no - #235

### CODE REVIEW

**Comment by priyankarpal** [comment]
try to fix the problem 

make sure your forked repo is up to date

also change the footer text `proudly open source`  

make social media icons at the end not center 



image

**Comment by Bharadwajshivam28** [comment]
okay

**Comment by Bharadwajshivam28** [comment]
there is a pizza icon beside Proudly Open Source we have to remove it or not

**Comment by priyankarpal** [comment]
> there is a pizza icon beside Proudly Open Source we have to remove it or not

remove it

**Comment by Bharadwajshivam28** [comment]
okay

**Pull request closed without merging**
