### PR TITLE
[style]: change footer UI design #601

### PR DESCRIPTION
**Pull request by ShreyaDhiman24**
## Related Issue

Issue Number #601 

## Description

Improved Footer design

## Screenshots

image

### CODE REVIEW

**Comment by priyankarpal** [comment]
remove shadows 

image

**Comment by priyankarpal** [comment]
may I offer a suggestion? Adding a descriptive title would greatly assist the maintainers in understanding and addressing the problem. Thank you for considering this.

**Comment by ShreyaDhiman24** [comment]
> may I offer a suggestion? Adding a descriptive title would greatly assist the maintainers in understanding and addressing the problem. Thank you for considering this.

Yeah sure! Could you please provide me detailed description of what your suggestion is as I'm unable to it clearly.

**Comment by priyankarpal** [comment]
> > may I offer a suggestion? Adding a descriptive title would greatly assist the maintainers in understanding and addressing the problem. Thank you for considering this.
> 
> Yeah sure! Could you please provide me detailed description of what your suggestion is as I'm unable to it clearly.

I've added

**Comment by ShreyaDhiman24** [comment]
> > > may I offer a suggestion? Adding a descriptive title would greatly assist the maintainers in understanding and addressing the problem. Thank you for considering this.
> > 
> > 
> > Yeah sure! Could you please provide me detailed description of what your suggestion is as I'm unable to it clearly.
> 
> I've added
> 
> image

Oh! I thought you are refering to website that's why didn't get it.

**Comment by priyankarpal** [comment]
> > > > may I offer a suggestion? Adding a descriptive title would greatly assist the maintainers in understanding and addressing the problem. Thank you for considering this.
> > > 
> > > 
> > > Yeah sure! Could you please provide me detailed description of what your suggestion is as I'm unable to it clearly.
> > 
> > 
> > I've added
> > image
> 
> Oh! I thought you are refering to website that's why didn't get it.

no no

**Comment by ShreyaDhiman24** [comment]
> remove shadows
> 
> image

image
Look it's good now?

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Pull request merged**
