### PR TITLE
Expanding Card Image Carousel: project addition by [buildwithaman] #735

### PR DESCRIPTION
**Pull request by buildwithaman**
Added my Project : Expanding Cards image Carousel

## Related Issue

#735 

## Description

I [buildwithaman] have added a project of mine here for issue number #735  

## Screenshots

projecthub

### CODE REVIEW

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Comment by priyankarpal** [comment]
please add your issue number

**Comment by priyankarpal** [comment]
> Hello @priyankarpal I am a GSSOC ' 23 contributor.
> 
> please let me know if there is any issue with my pull request

create a separate issue for this PR

**Comment by buildwithaman** [comment]
sorry but i have mentioned the issue number there which is #141

**Comment by priyankarpal** [comment]
> sorry but i have mentioned the issue number there which is #141

yeah, I just created this issue for the guide. You need to add your issue otherwise I guess your contribution will not be tracked by the GSSoC system

**Comment by buildwithaman** [comment]
hello @priyankarpal 
Sorry if my question seems lame 

According to what you have suggested me :
first I have to create a new issue for my project then make a new pull request mentioning the issue number of the issue I have created right now.

Right ???

**Comment by priyankarpal** [comment]
> hello @priyankarpal Sorry if my question seems lame
> 
> According to what you have suggested me : first I have to create a new issue for my project then make a new pull request mentioning the issue number of the issue I have created right now.
> 
> Right ???

create create issue for your projects addition & add issue number here

**Comment by buildwithaman** [comment]
ok thank you 


> > hello @priyankarpal Sorry if my question seems lame
> > According to what you have suggested me : first I have to create a new issue for my project then make a new pull request mentioning the issue number of the issue I have created right now.
> > Right ???
> 
> create an issue for the addition of your project & add the issue number here. You don't need to create new PR

ok thank you

**Comment by buildwithaman** [comment]
I have updated the issue number

can you check is any other issue there ??

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Pull request merged**
