### PR TITLE
[style]: fixed issue 861

### PR DESCRIPTION
**Pull request by jibola2588**
## Related Issue

fixed issue #861 

## Description

Changed the background color of the scroll button

## Screenshots

Screenshot (90)

### CODE REVIEW

**Comment by priyankarpal** [comment]
ig you have changed only the bg color I'm not seeing any major diff 😢

**Comment by priyankarpal** [comment]
> Yes, I wanted to animate the icon, but I did not include it in the issue raised, so I thought it was best to discuss it with you first

now you change the color but it's ok. but the height have not changed

**Comment by jibola2588** [comment]
sir, I feel the height is okay that was why I did not increase it, but I will do so if you want me to make adjustment to it

**Comment by priyankarpal** [comment]
> sir, I feel the height is okay that was why I did not increase it, but I will do so if you want me to make adjustment to it

ok ig it's looking good.

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Comment by jibola2588** [comment]
Thanks sir

**Pull request merged**
