### PR TITLE
Navbar for both Monitor and Mobile screen.

### PR DESCRIPTION
**Pull request by HarshPanchal26**
Made a Responsive Navbar  which allows to redirect from one page to another page

For Mobile Screen :

Screenshot (207)

For Monitor Screen 👍 
Screenshot (201)

Using Material UI and Tailwind .

### CODE REVIEW

**Comment by priyankarpal** [comment]
could you fix this problem? 

image

**Comment by priyankarpal** [comment]
also we are using Tailwind css 


image

**Comment by HarshPanchal26** [comment]
I'll solve this .Give me some time .

**Comment by priyankarpal** [comment]
Yeah sure take your time

**Comment by HarshPanchal26** [comment]
@priyankarpal  I commit again , just check once , and let me know if issue is still there , 

(I removed all the CSS file which I crated but , I have to make one change in index.css for "NavLink" , because it append active class to element whenever click event triggers .   )

**Comment by priyankarpal** [comment]
> @priyankarpal I commit again , just check once , and let me know if issue is still there ,
> 
> (I removed all the CSS file which I crated but , I have to make one change in index.css for "NavLink" , because it append active class to element whenever click event triggers . )

Looks Good 🎉

**Review by priyankarpal — APPROVED** [review]
Thanks for your contributions 🎉 ❤️

**Pull request merged**
