### PR TITLE
Change Pages URL

### PR DESCRIPTION
**Pull request by narayan2111**
## Related Issue

#624
## Description

This Project is designed as a part of the Coding Club initiative organized by the MCA Department of Galgotias College of Engineering and Technology. This Project involves creating a responsive design for the club. This Project has 3 contributors Narayan Dwivedi(Lead), Mayank Shukla, and Shivam Rai as a member of a team.

## Screenshots

Screenshot 2023-05-22 181847
Screenshot 2023-05-22 181906

### CODE REVIEW

**Comment by priyankarpal** [comment]
try add a valid issue number

**Comment by priyankarpal** [comment]
you added your projects here but you haven't added projects issues number

**Comment by priyankarpal** [comment]
> > You added your projects here but you haven't added the projects issues number
> 
> I updated the link, sir.

where I guess you have not created an issue for projects addition

**Comment by narayan2111** [comment]
> > > You added your projects here but you haven't added the projects issues number
> > 
> > 
> > I updated the link, sir.
> 
> where I guess you have not created an issue for projects addition

Sir, I have worked on the issue, assigned to me. The issue was already created with issue number #484

**Comment by narayan2111** [comment]
> This issue will fix another problem in this PR you have added your projects please check once more time.
> 
> image

I think I'm not able to understand the problem, Sir. Kindly guide me on how I can make this work.

**Comment by narayan2111** [comment]
> this issue will fix another problem in this PR you have added your projects please check once more time.
> 
> image

Sir, do I have to create a new issue regarding the addition of my projects under this Repository?

**Comment by priyankarpal** [comment]
i have added issue number #624

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Comment by narayan2111** [comment]
> Looks Good tada

Thank you sir!
Hope to learn many new things from you.

**Pull request merged**
