### PR TITLE
data: projects added by Abhinav kumar

### PR DESCRIPTION
**Pull request by Abhinavcode13**
Added a new project movie recommender system

## Related Issue
Closes the issue number #555 

## Description

A movie recommender system is a type of algorithmic software that provides personalized recommendations of movies to users based on their viewing history, preferences, and behavior.

### CODE REVIEW

**Comment by Abhinavcode13** [comment]
Please check the PR @priyankarpal 

Thankyou

**Comment by Abhinavcode13** [comment]
image
successfully deployed @priyankarpal

**Review by priyankarpal — CHANGES_REQUESTED** [review]
change the pr title to `data: projects added by your name`

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Pull request merged**
