### PR TITLE
chore: project addition by @Harshu467 #1334

### PR DESCRIPTION
**Pull request by Harshu467**
## Related Issue

@Harshu467
 #1334 
## Screenshots
image

## Checklist for projects addition 
 
- [x] My project has contribution guidelines.
- [x] My project has a Code of Conduct.
- [x] My project has a README file.
- [x] My project has a License.

---
Ready to Merge

### CODE REVIEW

**Review by priyankarpal — CHANGES_REQUESTED** [review]
you have added projects before so you don't need to add full code check the docs

**Comment by Harshu467** [comment]
> you have added projects before so you don't need to add full code check the docs

There were conflicts on that PR and henced I closed that PR and created nedw one , please check and merge.

**Comment by Harshu467** [comment]
I am facing conflicts because my pr not merge early and other pr added which cause this conflicts as in project.json my data is added in last but because u merge other PR it takes that place and I am facing this conficts evrytime . IT is request from my side please merge it and check it

**Comment by Harshu467** [comment]
I am resolving it

**Comment by Harshu467** [comment]
I have resolved the conflicts, Please merge it as soon as possible

**Comment by Harshu467** [comment]
@priyankarpal  Please Add labels of GSOC and level 1, I did not got points on GSOC leaderboard

**Pull request merged**
