### PR TITLE
Added Project Section

### PR DESCRIPTION
**Pull request by narayan2111**
## Related Issue

#484 

## Description

This Project is designed as a part of the Coding Club initiative organized by the MCA Department of Galgotias College of Engineering and Technology. This Project involves creating a responsive design for the club. This Project has 3 contributors Narayan Dwivedi(Lead), Mayank Shukla, and Shivam Rai as a member of a team.

## Screenshots

Screenshot 2023-05-22 181847
Screenshot 2023-05-22 181906

### CODE REVIEW

**Comment by priyankarpal** [comment]
you have added wrong issue number please add a valid one @narayan2111

**Comment by narayan2111** [comment]
> you have added wrong issue number please add a valid one @narayan2111

I'm confused with the issue number. It would be great if you could tell me the issue number I'm working on.
Thank you so much in advance sir.

**Comment by priyankarpal** [comment]
We regret to inform you that we are closing the pull request you submitted as it does not include an issue number and appears to be a case of spam. Kindly ensure to check our guidelines and procedures for creating pull requests in the future.

Thank you for your understanding.

**Comment by narayan2111** [comment]
> We regret to inform you that we are closing the pull request you submitted as it does not include an issue number and appears to be a case of spam. Kindly ensure to check our guidelines and procedures for creating pull requests in the future.
> 
> Thank you for your understanding.

I would be highly obliged to you sir for your kind response and, kindly look into this matter once again and do the needful help.
I hope you would understand sir.

**Pull request closed without merging**
