### PR TITLE
Fix: Icons are optimized

### PR DESCRIPTION
**Pull request by Sanchitbajaj02**
## Related Issue
As discussed in issue #995 the size of the icon libraries used in the project was over 70 MB. Because of that the project size as well as the web application is not optimized.

## Description
I use the lightweight icons library called [Feather Icons](https://feathericons.com/) and optimized the icons. If I miss something to update, just let me know.

### Light mode
image

### Dark mode
image

### CODE REVIEW

**Review by priyankarpal — CHANGES_REQUESTED** [review]
why is it failing?

**Comment by Sanchitbajaj02** [comment]
> why is it failing?

I don't know, let me fix the issues

**Comment by priyankarpal** [comment]
this branch has a conflicts error. Please resolve it

**Comment by Sanchitbajaj02** [comment]
> This branch has a conflicts error. Please resolve it

Please merge this branch. If you merge someone else's code first, there will again be a merge conflict

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Pull request merged**
