### PR TITLE
#267:make text visible on both dark and light mode

### PR DESCRIPTION
**Pull request by Ahtaxam**
issue #267: solved

 

- [x] I have tested my changes to ensure they work as expected
- [x] I have included documentation for any new features or changes
- [x] I have formatted my code according to the project's style guidelines
- [ ] I have written tests for any new features or changes
- [x] I have run the project's test suite and verified that all tests pass
- [ ] I have updated the README and any other relevant documentation
- [x] I have checked for any spelling or grammatical errors

### CODE REVIEW

**Comment by Deva-1903** [comment]
Can you please post the screenshots? @Ahtaxam

**Comment by Ahtaxam** [comment]
**in light mode**

Screenshot from 2023-04-25 10-53-11

**in dark mode**

Screenshot from 2023-04-25 10-53-36

**Comment by priyankarpal** [comment]
could you add footer colour to `#111827` for only dark mode?

**Comment by Ahtaxam** [comment]
footer background color in dark mode ?

**Comment by priyankarpal** [comment]
> footer background color in dark mode ?

yes use the navbar color for the footer for dark mode

**Comment by Ahtaxam** [comment]
Chnaged, looking appealing  now

Screenshot from 2023-04-25 11-18-26

.

**Comment by priyankarpal** [comment]
> Chnaged, looking appealing now
> 
> Screenshot from 2023-04-25 11-18-26
> 
> .

cool

**Review by priyankarpal — DISMISSED** [review]
Looks Good 🎉

**Review by priyankarpal — APPROVED** [review]

**Pull request merged**
