### PR TITLE
Solved Issue #482 [style]: Make the navbar sticky and prominent

### LINKED ISSUE #482: [style]: Make the navbar sticky and prominent
### What's the style idea?

Make the navbar sticky so that it comes down with the user when they scroll down and also to make it more prominent looking we can make the background of the navbar blur and translucent,This would make the navbar look more alluring and attractive

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by vishnu9865**
Close #482 

## Related Issue
#482 [Issue Link](https://github.com/priyankarpal/ProjectsHut/issues/482)

## [feat] Make the navbar Sticky with Themes
 - Made the navbar sticky.
 - navbar has a backdrop blur for glassy transparent effect
 - The background color of the navbar changes with light/dark theme at 50% opacity for better UI/UX.

## Screenshots
| Desktop | Mobile |
|---|---|
| localhost_5173_ (1) | localhost_5173_ (2) |
| localhost_5173_ (4) | localhost_5173_ (3) |

- kindly do add GSSOC23 tags in the related issue.
- Thank you for providing me with this opportunity for contributing to Open Source.

### CODE REVIEW

**Comment by priyankarpal** [comment]
> @priyankarpal, One doubt 'pnpm format' has modified most files, is it okay to put up a pull request. image

yeah also add commits

**Comment by vishnu9865** [comment]
@priyankarpal Sir, done the changes. Waiting for any other changes if required.
Thank you.

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Comment by priyankarpal** [comment]
> Thank you @priyankarpal for accepting my contribution. Sir, Is there any discord servers for this project so I can contribute more ?

currently no

**Pull request merged**
