### PR TITLE
data: project addition by @shagunZ #899

### PR DESCRIPTION
**Pull request by shagunZ**
## Description
Added a project MovieApp  built with React, leveraging APIs to provide users with an extensive collection of movies and comprehensive search options. 

## Screenshots

Screenshot (112)

### CODE REVIEW

**Comment by priyankarpal** [comment]
please add the issue number.

**Comment by shagunZ** [comment]
issue number #900

**Comment by priyankarpal** [comment]
> issue number #900

this the PR number

**Comment by shagunZ** [comment]
issue number #899

**Review by priyankarpal — APPROVED** [review]
Thank you for contributing your projects here 👏🏻 🎉

**Pull request merged**
