### PR TITLE
chore: project addition by Harshu467 #1869

### PR DESCRIPTION
**Pull request by Harshu467**
## Project Addition
Regarding Issue Number #1869 

## Description

Added Machine Learning Project of water Quality Prediction

### CODE REVIEW

**Comment by Harshu467** [comment]
Please check and Merge

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Comment by Harshu467** [comment]
Please Add label of GSOC and level @priyankarpal

**Comment by priyankarpal** [comment]
> Please Add label of GSOC and level @priyankarpal

We are not providing any labels for project additions as they are not associated with solving any issues.( according to gssoc23 rules)

**Comment by Harshu467** [comment]
So they dont count for GSOC score?

**Comment by priyankarpal** [comment]
> So they dont count for GSOC score?

nope. only for projects addition we're not providing any labels

**Pull request merged**
