### PR TITLE
Added a new project in the projects.json file #141

### PR DESCRIPTION
**Pull request by ayushlohmod**
i have added a new project in the project.json file

### CODE REVIEW

**Comment by ayushlohmod** [comment]
I'm in GSSOC'23

**Comment by priyankarpal** [comment]
please add issue number without issue number we can't merge this PR

**Comment by ayushlohmod** [comment]
#141

**Comment by ayushlohmod** [comment]
Added issue number kindly check

**Comment by ayushlohmod** [comment]
Done! can you check again

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Pull request merged**
