### PR TITLE
chore: project addition by vrundraval24 #2216

### PR DESCRIPTION
**Pull request by vrundraval24**
## Related Issue

#2216

### CODE REVIEW

**Comment by priyankarpal** [comment]
there is no issue number

**Comment by vrundraval24** [comment]
what issue number should i assign i was confused

**Comment by priyankarpal** [comment]
> what issue number should i assign i was confused

in open source contribution, we create an issue first and then create a PR after getting assigned.

**Comment by vrundraval24** [comment]
i have added issue number, please check it

**Comment by vrundraval24** [comment]
Is there any mistake, should i wait for getting assigned to a issue we created and then commit into it??

**Review by priyankarpal — APPROVED** [review]

**Pull request merged**
