### PR TITLE
project addition: added react project

### PR DESCRIPTION
**Pull request by sshiwangi**
Fixes Issue #468 
## Description

Added a React Quiz App that allows users to select one answer out of a set of four answer choices for each question. By selecting the appropriate option, users can swiftly evaluate their performance and receive a calculated score based on the number of correct answers.

## Screenshots

Screenshot 2023-05-20 111629

Screenshot 2023-05-20 111909

### CODE REVIEW

**Comment by priyankarpal** [comment]
without the issue number, we are unable to merge this PR.

**Comment by sshiwangi** [comment]
> without the issue number, we are unable to merge this PR.

Oh, I'm so sorry I though we do not need to create an issue for adding projects. Can I create an issue now? Will it be eligible to merge?

**Comment by priyankarpal** [comment]
> > without the issue number, we are unable to merge this PR.
> 
> Oh, I'm so sorry I though we do not need to create an issue for adding projects. Can I create an issue now? Will it be eligible to merge?

you can create an issue & add the issue number also

**Comment by sshiwangi** [comment]
> > > without the issue number, we are unable to merge this PR.
> > 
> > 
> > Oh, I'm so sorry I though we do not need to create an issue for adding projects. Can I create an issue now? Will it be eligible to merge?
> 
> you can create an issue & add the issue number also

ok

**Comment by sshiwangi** [comment]
> > > without the issue number, we are unable to merge this PR.
> > 
> > 
> > Oh, I'm so sorry I though we do not need to create an issue for adding projects. Can I create an issue now? Will it be eligible to merge?
> 
> you can create an issue & add the issue number also

I added the Issue number, please review it.

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉 there are some spacing issue don't worry

**Pull request merged**
