### PR TITLE
feature/styling of navbar links on hover and focus

### PR DESCRIPTION
**Pull request by Amitavpanda**
## Description

This pull request aims to resolve the styling issue mentioned in the issue #373. The current implementation of the navbar lacks visual feedback when interacting with the navlinks. I have made the necessary changes to enhance the user experience.

You can refer the video to see the changes I made.

## Video of the Implementation

https://github.com/Amitavpanda/ProjectsHut/assets/56599943/cf586e59-d4cf-4cfe-ada6-fd7c91815261

Please review and merge this pull request to incorporate the suggested changes. Let me know if any further modifications or adjustments are needed.

Thank you for your consideration and for maintaining this open-source project.

### CODE REVIEW

**Comment by priyankarpal** [comment]
so you have used `npm` instead of `pnpm`. Use `pnpm` also create a fresh PR there are some errors.

**Comment by Amitavpanda** [comment]
> so you have used `npm` instead of `pnpm`. Use `pnpm` also create a fresh PR there are some errors.

**Comment by Amitavpanda** [comment]
> so you have used `npm` instead of `pnpm`. Use `pnpm` also create a fresh PR there are some errors.

first i used npm , then i used pnpm after reading the docs.

**Comment by priyankarpal** [comment]
> > so you have used `npm` instead of `pnpm`. Use `pnpm` also create a fresh PR there are some errors.
> 
> first i used npm , then i used pnpm after reading the docs.

please follow contributing guide lines first

**Pull request closed without merging**
