### PR TITLE
feat: Added animation to cards

### LINKED ISSUE #1770: Add hover to make it attractive
### What happened?

image

I would like add hover effects to this section. Please assign it to me under gssoc'23

### Add screenshots

-

### What browsers are you seeing the problem on?

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by akanksha984**
## Related Issue
Closes #1770 

## Screenshots
image

### CODE REVIEW

**Comment by akanksha984** [comment]
@priyankarpal does it look good?

**Comment by priyankarpal** [comment]
> @priyankarpal does it look good?

will check soon

**Review by priyankarpal — CHANGES_REQUESTED** [review]
@akanksha984 I think if we add border it will be good. I tried it in local & it's ok. just we need to change the code a little bit. 

add the full code after 42 no. line 


```
              <div key={feature.name} className=" p-5 hover:border border-gray-600  rounded">
                <div className="relative pl-16">
                  <dt className="text-base font-semibold leading-7 text-white">
                    <div className="absolute left-0 top-0 flex h-10 w-10 items-center justify-center rounded-lg bg-primary">
                      <feature.icon
                        className="h-6 w-6 text-white"
                        aria-hidden="true"
                      />
                    </div>
                    {feature.name}
                  </dt>
                  <dd className="mt-2 text-base leading-7 text-gray-400">
                    {feature.description}
                  </dd>
                </div>
              </div>
```

**Comment by akanksha984** [comment]
Check it now @priyankarpal

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Pull request merged**
