### PR TITLE
data: projects addition by vaibhav-xt

### PR DESCRIPTION
**Pull request by vaibhav-xt**
## Description
   Issue Number #463
   I added my portfolio project. 

## Screenshots
Screenshot (408)

### CODE REVIEW

**Comment by priyankarpal** [comment]
without the issue number, we are unable to merge this PR.

Check the [Contributing.md](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)

**Comment by vaibhav-xt** [comment]
> without the issue number, we are unable to merge this PR.
> 
> Check the [Contributing.md](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)

Sorry for that now I added the issue Number.

**Comment by priyankarpal** [comment]
> > without the issue number, we are unable to merge this PR.
> > Check the [Contributing.md](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
> 
> Sorry for that now I added the issue Number.

create an issue for your project & add the issue number here. Avoid adding mine issue numbers. Otherwise, it will create problem in GSSoc'23

**Comment by vaibhav-xt** [comment]
> > > without the issue number, we are unable to merge this PR.
> > > Check the [Contributing.md](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
> > 
> > 
> > Sorry for that now I added the issue Number.
> 
> create an issue for your project & add the issue number here. Avoid adding mine issue numbers. Otherwise, it will create problem in GSSoc'23

Ok I am doing that.

**Comment by priyankarpal** [comment]
> > > > without the issue number, we are unable to merge this PR.
> > > > Check the [Contributing.md](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
> > > 
> > > 
> > > Sorry for that now I added the issue Number.
> > 
> > 
> > create an issue for your project & add the issue number here. Avoid adding mine issue numbers. Otherwise, it will create problem in GSSoc'23
> 
> I hope now every thing is ok.

just small changes are needed. format files using `pnpm format`

**Comment by vaibhav-xt** [comment]
I think everything is right now. Hoping

**Comment by priyankarpal** [comment]
> I think everything is right now. Hoping

you can add your social media links later.

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Comment by vaibhav-xt** [comment]
Thanks for helping. I created one issue please look at this issue. #460

**Pull request merged**
