### PR TITLE
Implemented Pagination

### PR DESCRIPTION
**Pull request by SteveSayantan**
## Description

As described in #178 , a pagination system has been added. Also, line clamp is added to Product Card title.

## Screenshots

Pagination_projectHub

## Checklist

Please review and check off the following items before submitting your PR:

 

- [x] I have tested my changes to ensure they work as expected
- [x] I have included documentation for any new features or changes
- [x] I have formatted my code according to the project's style guidelines
- [x] I have written tests for any new features or changes
- [x] I have run the project's test suite and verified that all tests pass
- [x] I have updated the README and any other relevant documentation
- [x] I have checked for any spelling or grammatical errors

## Additional Information

In case of tech-labels in Product-Card, usage of line-clamp property shows inappropriate behavior (as shown below) . Therefore, JS is used for maintaining the length of the line.
Disturbance_lineClamp

### CODE REVIEW

**Comment by priyankarpal** [comment]
On the projects page change the total projects to 9 instead of 10. 

image

**Comment by priyankarpal** [comment]
- also, please don't add inline functions 

image


- using inline functions can also lead to performance issues, particularly if you use them inside render functions. This is because every time the component re-renders, a new function is created, which can be expensive in terms of performance.

- to optimize performance, consider extracting the function out of the component and defining it as a separate function outside of the component. This way, the function will only be created once and reused across renders.

**Comment by priyankarpal** [comment]
- please don't use the anonymous function with the `onclick` event
Screenshot from 2023-04-14 12-04-46

- using inline functions can also lead to performance issues, particularly if you use them inside render functions. 

- to optimize performance, consider extracting the function out of the component and defining it as a separate function outside of the component.

**Comment by priyankarpal** [comment]
> > * please don't use the anonymous function with the `onclick` event
> >   Screenshot from 2023-04-14 12-04-46
> > * using inline functions can also lead to performance issues, particularly if you use them inside render functions.
> > * to optimize performance, consider extracting the function out of the component and defining it as a separate function outside of the component.
> 
> I have replaced the anonymous functions with named functions. But couldn't extract all these outside component except the paginate function. ProjectHub_Review1
> 
> And the buttons look like this Projecthub_review
> 
> Let me know if further changes are necessary

okk just push it

**Comment by SteveSayantan** [comment]
> > > * please don't use the anonymous function with the `onclick` event
> > >   Screenshot from 2023-04-14 12-04-46
> > > * using inline functions can also lead to performance issues, particularly if you use them inside render functions.
> > > * to optimize performance, consider extracting the function out of the component and defining it as a separate function outside of the component.
> > 
> > 
> > I have replaced the anonymous functions with named functions. But couldn't extract all these outside component except the paginate function. ProjectHub_Review1
> > And the buttons look like this Projecthub_review
> > Let me know if further changes are necessary
> 
> okk just push it

Done 👍

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Pull request merged**
