### PR TITLE
chore: project addition by Killer2OP #1354

### PR DESCRIPTION
**Pull request by Killer2OP**
## Related Issue

ISSUE #1354 

## Description

The project has been added.

## Screenshots

image

## Checklist for projects addition 
 
- [X] My project has contribution guidelines.
- [X] My project has a Code of Conduct.
- [X] My project has a README file.
- [ ] My project has a License.

---

Please note that if your project doesn't meet these requirements, your PR may be closed. Make sure to include these elements in your project before submitting the PR.

### CODE REVIEW

**Review by priyankarpal — CHANGES_REQUESTED** [review]
your project doesn't have a Code of conduct, Contributing guide &  License without these requirements I can't merge this PR

**Comment by Killer2OP** [comment]
> your project doesn't have Code of conduct, Contributing guide & License without these requirements I can't merge this PR

wait let me create those.

**Comment by Killer2OP** [comment]
> your project doesn't have Code of conduct, Contributing guide & License without these requirements I can't merge this PR

DONE!!

**Review by priyankarpal — APPROVED** [review]
cool 🔥

**Pull request merged**
