### PR TITLE
Docs: translated into kannada #918

### PR DESCRIPTION
**Pull request by Bhanuteja01**
## Related Issue
#918

## Description
docs are transalted into kannada

### CODE REVIEW

**Comment by Bhanuteja01** [comment]
@priyankarpal  
can  you tell me whats the issue in this pr ?

**Comment by priyankarpal** [comment]
> @priyankarpal can you tell me whats the issue in this pr ?

what is this?  😢 

image

**Comment by Bhanuteja01** [comment]
which file its look like this

**Comment by priyankarpal** [comment]
> which file its look like this

translated docs

**Comment by Bhanuteja01** [comment]
once check again now
from myside all good

**Review by priyankarpal — APPROVED** [review]
yeah well & good on mobile but not on my laptop

**Pull request merged**
