### PR TITLE
style :  improved the project card design 

### PR DESCRIPTION
**Pull request by AshutoshDash1999**
## Related Issue
#368 

## Description
- removed black border
- add shadow on hover
- changed button gradient

## Screenshots
updated project card style

### CODE REVIEW

**Comment by priyankarpal** [comment]
## Changes required
- remove the border for only dark mode.
- add hover effect for dark mode also
- format files using `pnpm format`

**Comment by priyankarpal** [comment]
this branch has a conflict error. please resolve it

**Comment by AshutoshDash1999** [comment]
ok i am working on it

**Comment by priyankarpal** [comment]
this branch has a conflict error. Please solve the error.

**Comment by AshutoshDash1999** [comment]
> ## Changes required
> * remove the border for only dark mode.

@priyankarpal so I should keep the project cards in a light mode with borders?

Like keep the card in light mode as it is..right??
image

If the border is important, should I suggest making it lighter? Like light grey kind of.

**Comment by AshutoshDash1999** [comment]
> this branch has a conflict error. Please solve the error.

conflict resolved

**Comment by priyankarpal** [comment]
format these files using `pnpm format`

[warn] .github/ISSUE_TEMPLATE/project-add.yml
[warn] src/components/ProjectCard.jsx
[warn] src/DB/projects.json

**Comment by priyankarpal** [comment]
@AshutoshDash1999 light mode is ok 
image

just remove border fro dark mode & add a little bit of hover effect(shadow)

**Comment by priyankarpal** [comment]
could you share your progress on this issue?

**Comment by priyankarpal** [comment]
Based on the guidelines of **GSSoC'23**, it appears that this particular issue has not been resolved within the past few days. As it involves a simple pull request, we would like to kindly inform you that we will be closing this issue. 

If you still wish to include your projects, we encourage you to create a new issue and submit a pull request accordingly. Please ensure to review the [contributing guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md) 

Thank you for your understanding.

**Comment by AshutoshDash1999** [comment]
Hi @priyankarpal I am sorry not to give any update on this. I havemy major project submission tomorrow. I also faced some issues while pushing the code. Will you please reconsider reassigning this issue to me?

**Comment by AshutoshDash1999** [comment]
Hi @priyankarpal I am sorry not to give any update on this. I have my major project submission tomorrow. I also faced some issues while pushing the code. Will you please reconsider reassigning this issue to me?

**Comment by priyankarpal** [comment]
> Hi @priyankarpal I am sorry not to give any update on this. I have my major project submission tomorrow. I also faced some issues while pushing the code. Will you please reconsider reassigning this issue to me?

we are thinking of redesigning the card so now it's not needed.

**Pull request closed without merging**
