### PR TITLE
docs: updated twitter link in CODE_OF_CONDUCT.md by [adarsh-jha-dev]

### PR DESCRIPTION
**Pull request by adarsh-jha-dev**
## Related Issue

There are no existing issues for this, i just wanted to see the twitter of @priyankarpal  so i came across this issue.

## Description

This PR resolves the problem with the link provided for twitter account of @priyankarpal , it had a small typo and it was not redirecting to the correct page. (It was not a valid URL). I corrected it.

## Screenshots

No screenshots required, you can check the CODE_OF_CONDUCT.md

### CODE REVIEW

**Review by RitikKumarParvat — APPROVED** [review]

**Comment by priyankarpal** [comment]
@adarsh-jha-dev yeah! it was a typo. 
image


now it's working thanks for your contribution.

**Review by priyankarpal — APPROVED** [review]

**Comment by priyankarpal** [comment]
@adarsh-jha-dev I disabled the issue tab to reduce spam in this hacktoberfest season. Though this project is not part of hacktoberfest; people are doing spam PR so... issue tab will be available after this month.

**Comment by RitikKumarParvat** [comment]
great

**Comment by adarsh-jha-dev** [comment]
> @adarsh-jha-dev I disabled the issue tab to reduce spam in this hacktoberfest season. Though this project is not part of hacktoberfest; people are doing spam PR so... issue tab will be available after this month.

No issues .

**Pull request merged**
