### PR TITLE
Update projects.json

### PR DESCRIPTION
**Pull request by sonustar**
I am updating with my project

## Description

I am providing a project that will keep track of how many hours a student will study, I will upload the URL soon of the app it is a study time counter. Please accept my pull request.
Screenshot 2023-05-20 190244

### CODE REVIEW

**Comment by sonustar** [comment]
thanks please accept it i will just deploy and provide you the app link

**Comment by priyankarpal** [comment]
so we can't approve this PR currently there is no issue number.

**Comment by sonustar** [comment]
if i provide the issue number will you please accept i will be providing again

**Comment by priyankarpal** [comment]
> if i provide the issue number will you please accept i will be providing again

yeah add the issue number

**Comment by priyankarpal** [comment]
We regret to inform you that we are closing the pull request you submitted as it does not include an issue number and appears to be a case of spam. Kindly ensure to check our guidelines and procedures for creating pull requests in the future.

Thank you for your understanding.

**Pull request closed without merging**
