### PR TITLE
style: Animated Landing Page

### LINKED ISSUE #1823: chore: Adding Animations to the website
### What feature?

Currently The Page Loads Statically But In Order To Improve the User Experience, We Can Add Animations To The Website. 

### Add screenshots

Sure, Once Get Assigned 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Souravvmishra**
## Description

Resolved #1823

Added animation to the landing page. I found these value good, if you have any issue or want any change in animation, I'll be more than happy to do so.

### CODE REVIEW

**Review by priyankarpal — CHANGES_REQUESTED** [review]
@Souravvmishra please use `pnpm i` to install all packages

**Comment by Souravvmishra** [comment]
@priyankarpal Can you please, what else needs to be done?

**Comment by priyankarpal** [comment]
> @priyankarpal Can you please, what else needs to be done?

will check soon

**Comment by priyankarpal** [comment]
> > @priyankarpal Can you please, what else needs to be done?
> 
> will check soon

we need to add animations for all pages( docs, projects page, user profile)

**Comment by Souravvmishra** [comment]
Any Update?

**Comment by priyankarpal** [comment]
> yup, adding animations require checking possible values to find the best one that fits all the screen sizes. I would like to create one PR for each page. If you allow 😅


> Any Update?


I will check soon

**Review by priyankarpal — CHANGES_REQUESTED** [review]
@Souravvmishra use this command `pnpm install --no-frozen-lockfile` & push

**Comment by Souravvmishra** [comment]
@priyankarpal Please Review Brother

**Comment by priyankarpal** [comment]
> @priyankarpal Please Review Brother

yeah sure

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Pull request merged**
