### PR TITLE
Docs: add contributors graph with dropdown

### PR DESCRIPTION
**Pull request by 0xabdulkhalid**
## Related Issue
- Closes/Fixes: #1022 

## Description
- Added repository Contributors graph which shows an overall picture of all contributors who contributed to this project/repository
- Additionally we added a dropdown menu using `details` & `summary`, So that the Graph itself will not consume more space until we open it to see it

## Screenshots
image
image

### CODE REVIEW

**Comment by 0xabdulkhalid** [comment]
I have changed the PR name due to the conflicts, i inspected the prefixes mentioned in `pr-title-checker-config` file.

Now everything's clear!

**Comment by 0xabdulkhalid** [comment]
Hello @priyankarpal, can i know why this PR is still not merged ?

**Comment by priyankarpal** [comment]
> Hello @priyankarpal, can i know why this PR is still not merged ?

will merge soon. I was busy 😢

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Pull request merged**
