### PR TITLE
:white_check_mark: Setup tests #290

### PR DESCRIPTION
**Pull request by Syed-Ali-Abbas-Zaidi**
## Description

This PR setup unit tests.

## Checklist

Please review and check off the following items before submitting your PR:

 

- [x] I have tested my changes to ensure they work as expected
- [ ] I have included documentation for any new features or changes
- [x] I have formatted my code according to the project's style guidelines
- [x] I have written tests for any new features or changes
- [x] I have run the project's test suite and verified that all tests pass
- [ ] I have updated the README and any other relevant documentation
- [x] I have checked for any spelling or grammatical errors

### CODE REVIEW

**Comment by priyankarpal** [comment]
could you add the issue number to the description?

**Comment by Syed-Ali-Abbas-Zaidi** [comment]
@priyankarpal, This PR setups tests and I have added very basic level test cases for some pages, moving forward we can expand these unit tests. I plan to add a Quality Check workflow once this test setup merges. After that, on every PR these Quality checks will execute and ensure all test cases are passing.


Uploading Screen Recording 2023-04-27 at 10.26.30 PM.mov…

**Comment by priyankarpal** [comment]
> @priyankarpal, This PR setups tests and I have added very basic level test cases for some pages, moving forward we can expand these unit tests. I plan to add a Quality Check workflow once this test setup merges. After that, on every PR these Quality checks will execute and ensure all test cases are passing.
> 
> Uploading Screen Recording 2023-04-27 at 10.26.30 PM.mov…

ok ok but we can use eslint too

**Comment by Syed-Ali-Abbas-Zaidi** [comment]
https://user-images.githubusercontent.com/88369802/234946198-5ebe9ba9-d28b-4540-a6f1-87347eb6db54.mov

Eslint only ensures the code standards that we are already achieving with `prettier`. Unit tests make sure that pages/components are rendering properly even after the new changes of a particular PR.

**Comment by priyankarpal** [comment]
> Screen.Recording.2023-04-27.at.10.26.30.PM.mov 
> Eslint only ensures the code standards that we are already achieving with `prettier`. Unit tests make sure that pages/components are rendering properly even after the new changes of a particular PR.

yeah cool, I also tested your branch. 
but I have a question there are some files added such as `src/pages/AddYourProjectsGuide.test.jsx` Doesn't it create confusion for newbies?

**Comment by Syed-Ali-Abbas-Zaidi** [comment]
For newbies, Yes. But It's good practice to name the test file after the name of the component. One thing we can do is create a `__tests__` folder at the root and move these test files to that folder. For example `__tests__` -> `pages` -> `someComponent.test.jsx`. WDYT?

**Comment by priyankarpal** [comment]
> For newbies, Yes. But It's good practice to name the test file after the name of the component. One thing we can do is create a `__tests__` folder at the root and move these test files to that folder. For example `__tests__` -> `pages` -> `someComponent.test.jsx`. WDYT?

yes this is good idea. 

Also, we need to add hooks so that run `pnpm test`
need to mention to docs

**Comment by priyankarpal** [comment]
should we add the `pnpm test` to the `.husky` folder?

**Comment by Syed-Ali-Abbas-Zaidi** [comment]
> 

No, As we have to explicitly press `q` to exit unit tests, Husky will get stuck at that screen. What we can do is create a github action that executes `pnpm test` on the PR's same as `Greetings/Json check`.

**Comment by priyankarpal** [comment]
> > 
> 
> No, As we have to explicitly press `q` to exit unit tests, Husky will get stuck at that screen. What we can do is create a github action that executes `pnpm test` on the PR's same as `Greetings/Json check`.

ok, will you create?

**Comment by Syed-Ali-Abbas-Zaidi** [comment]
Yes, What do you suggest, Should I create a separate PR for that or Should I push it in this PR?

**Comment by priyankarpal** [comment]
cool merging it

**Pull request merged**
