### PR TITLE
style: Animated docs

### LINKED ISSUE #1903: Animating The Docs Section
### What feature?

Animating The Docs Part

### Add screenshots

IMG_20230730_101032

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Souravvmishra**
## Related Issue
closed #1903 

## Description
Animated the docs section

### CODE REVIEW

**Review by priyankarpal — CHANGES_REQUESTED** [review]
not showing for `cd ProjectsHut`

https://github.com/priyankarpal/ProjectsHut/assets/88102392/87840fa7-2935-4f2d-aef7-82d08523a7e1

**Comment by Souravvmishra** [comment]
@priyankarpal Done Bro. It was really a needle in the husk.

**Review by priyankarpal — APPROVED** [review]

**Comment by priyankarpal** [comment]
@Souravvmishra For secure collaboration, remember to check out GitHub's commit signature verification feature. It helps ensure the authenticity of commits and prevents tampering.

Learn how it works: [GitHub Docs](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification)

Happy coding! 😄

**Comment by Souravvmishra** [comment]
That sounds interesting. TBH I never heard about that. Thanks For The Suggestions Bro. I'll make sure I follow it for next PRs

**Pull request merged**
