### PR TITLE
Added: Project Spotify Clone

### PR DESCRIPTION
**Pull request by vishnu-mouli-102408**
## Related Issue
#478

### CODE REVIEW

**Comment by priyankarpal** [comment]
add the issue number after I can merge this PR

**Comment by vishnu-mouli-102408** [comment]
> add the issue number after I can merge this PR

please tell me how to add the issue number

**Comment by vishnu-mouli-102408** [comment]
> add the issue number after I can merge this PR

Issue Number -> #478

**Comment by priyankarpal** [comment]
this branch has a conflicts error. Please resolve it

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Pull request merged**
