### PR TITLE
refactor: enhancing ProjectList.tsx 🪄 ✨ 

### LINKED ISSUE #1970: [Refactor]: add project link to name instead of github logo ⚒️✨
### File Name

components/projects/ProjectList.tsx

### Reason for Refactoring the Code

- The visitor's can't touch the Project's Name to navigate to the Project's Page.
- Providing the Project link via Github Logo is tend to confusing to the user, Everyone will hover the card the touches the Project's Name.
- And the Github Logo's hover state also not looks good, we need to change it's hover state from `#6B7280` to `#A66EFC`.
- Otherwise we can change the link from Github Logo to the Card list items itself, It will be more engaging to the User.
- Let me know your thoughts!

### Current State (Video)
https://github.com/priyankarpal/ProjectsHut/assets/92252895/1b883c47-f39b-4129-8d70-8f947dc87ed7

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by 0xabdulkhalid**
## Related Issue

Close #1970

## Description
- Refactored the `ProjectList.tsx` Component.
- Replaced Github icon with External Link icon.
- Implement hover feature for Cards and UI enhancements.

## Demonstrating Video

https://github.com/priyankarpal/ProjectsHut/assets/92252895/5d45ea96-32ff-4b25-ac9c-5664f2cf4ebb

### CODE REVIEW

**Review by priyankarpal — CHANGES_REQUESTED** [review]
remove this hover effect & add the previous hover border

**Comment by 0xabdulkhalid** [comment]
The Border could not give visual clue for the User, Who has color disability.

So that i additionally added transform scale to highlight the active element.

Let me know your thoughts @priyankarpal

**Comment by priyankarpal** [comment]
> The Border could not give visual clue for the User, Who has color disability.
> 
> So that i additionally added transform scale to highlight the active element.
> 
> Let me know your thoughts @priyankarpal

just add the previous hover border effect also,I think we don't need to add scale the project card

**Comment by 0xabdulkhalid** [comment]
Successfully reverted 🔁

**Comment by 0xabdulkhalid** [comment]
After merging this PR make sure to check out this issue #1969,

You can assign that to me once you verified it.

**Review by priyankarpal — APPROVED** [review]

**Pull request merged**
