### PR TITLE
chore: Project Addition by mohit-dhote #2193

### PR DESCRIPTION
**Pull request by mohitd404**
Add a new project to the list
I want to add my project.
Fixed:- #2193
Record
✅ I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
✅ I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
✅ I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by priyankarpal** [comment]
there is no issue number

**Comment by mohitd404** [comment]
> there is no issue number

I have added the issue no @priyankarpal please review the changes! thank you!

**Comment by priyankarpal** [comment]
there are conflicts error please fix them

**Comment by mohitd404** [comment]
> there are conflicts error please fix them

done

**Comment by priyankarpal** [comment]
Due to various issues, I will have to close the PR. However, you can resubmit it after hacktoberfest.

**Pull request closed without merging**
