### PR TITLE
data: projects addition by akshaya #927

### PR DESCRIPTION
**Pull request by akshaya-hub**
update project
issue number: #927

### CODE REVIEW

**Comment by priyankarpal** [comment]
please add the issue number

**Comment by akshaya-hub** [comment]
@priyankarpal added the issue number

**Review by hariketsheth — CHANGES_REQUESTED** [review]
@akshaya-hub 
Please refer how `projects` are added in JSON file before by others. 
From Line 1886 

```
},
{
      github_username: "akshaya-hub",
      Social_media: {
        gitHub: "https://github.com/akshaya-hub",
        LinkedIn: "https://www.linkedin.com/in/akshaya-madhuri-adireddy-028019213/",
        Twitter: "https://twitter.com/AKSHAYA96187678"
      },
      Projects: [
        {
          link: "https://github.com/akshaya-hub/personality-prediction",
          title: "Personality Analysis",
          description: "In this project, one can analyze the personality of different persons and can calculate the accuracies of personalities using different algorithms",
          tech: ["Python", "Machine Learning"]
        },

      ]
  }
]
```

The closing bracket on Line 1887 should come after you have added your project.

**Review by hariketsheth — CHANGES_REQUESTED** [review]
Also the fields such as `github_username`, `Social_media`, `Projects` should all be mentioned with quotes " "  as `"github_username"`, `"Social_media"`, `"Projects"`

**Comment by priyankarpal** [comment]
> Also the fields such as `github_username`, `Social_Media`, `Projects` should all be mentioned with quotes " "

@akshaya-hub if you want you can close this PR & create a fresh PR also, please follow  the [contributing docs](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)

otherwise you can update the PR

**Review by priyankarpal — APPROVED** [review]
Thank you for contributing your projects here 👏🏻 🎉

**Pull request merged**
