### PR TITLE
Fixed dev img above the footer on mobile view

### LINKED ISSUE #242: 🐞Bug: Fix the image on moblie view
**Describe the bug**
Fix the image shown in the screenshot on mobile view 

**To Reproduce**
Set Screen size to mobile view

**Screenshots**

Screenshot (314)

**Desktop (please complete the following information):**

- OS: [Windows]
- Browser [chrome]

### PR DESCRIPTION
**Pull request by Deva-1903**
## Description
Closes #242 

## Screenshots

Screenshot (315)

- [x] I have tested my changes to ensure they work as expected
- [ ] I have included documentation for any new features or changes
- [x] I have formatted my code according to the project's style guidelines
- [ ] I have written tests for any new features or changes
- [x] I have run the project's test suite and verified that all tests pass
- [ ] I have updated the README and any other relevant documentation
- [x] I have checked for any spelling or grammatical errors

### CODE REVIEW

**Review by priyankarpal — CHANGES_REQUESTED** [review]
we are using Tailwind css so try to add Tailwind CSS.

**Comment by Deva-1903** [comment]
```
@media only screen and (max-width: 768px) {
  .dev-img-parent-class {
    height: 40vh;
  }

  .dev-img-class {
    width: 80%;
    height: auto;
    max-width: 300px;
    top: 40%;
    left: 50%;
    transform: translate(-35%, 0%);
  }
}  
```

how to write this in tailwind?

**Comment by priyankarpal** [comment]
ok, I'm merging it now. I will look into it later.

**Review by priyankarpal — APPROVED** [review]
Completed. Thanks for your contributions 🎉 ❤️

**Comment by Deva-1903** [comment]
I am looking into it. If I change them I will open a PR. @priyankarpal

**Comment by priyankarpal** [comment]
> I am looking into it. If I change them I will open a PR. @priyankarpal

ok cool

**Pull request merged**
