### PR TITLE
chore: Filpkart data scrap project

### PR DESCRIPTION
**Pull request by Sushilverma002**
## Related Issue
close issue-> #2021 
## Screenshots

image

### CODE REVIEW

**Comment by Sushilverma002** [comment]
@priyankarpal have a look!!!

**Comment by priyankarpal** [comment]
this branch has a conflicts error. Please resolve it

**Comment by priyankarpal** [comment]
> this branch has a conflicts error. Please resolve it

solved by me

**Review by priyankarpal — APPROVED** [review]

**Comment by Sushilverma002** [comment]
@priyankarpal please add level label and GGSoC'23 label

**Comment by Sushilverma002** [comment]
@priyankarpal please add GGSoC'23 label and level label so that I get points for this pr.

**Comment by priyankarpal** [comment]
We are not providing any labels for project additions as they are not associated with solving any issues.( according to gssoc23 rules)

**Pull request merged**
