### PR TITLE
[style]: Responsive Developer Profile #602

### PR DESCRIPTION
**Pull request by parasss19**
## Related Issue

Resloved the issue #602

Made Changes in 
1 Project.jsx
2 Footer.jsx

## Description

In Cards  -> More -> Developer Profile . It is not responsive and break in different screens.
I made the Developer Profile fully responsive in all  screens

## Screenshots

https://github.com/priyankarpal/ProjectsHut/assets/101205226/b3ddaac7-379d-4994-bcf3-8a558676d34f

### CODE REVIEW

**Comment by parasss19** [comment]
@priyankarpal please review it once

**Review by priyankarpal — CHANGES_REQUESTED** [review]
remove extra padding from profile card

image

**Comment by parasss19** [comment]
> remove extra padding from profile card
> 
> image

side paddings on large screens?

**Comment by parasss19** [comment]
hii @priyankarpal i am not able to send PR after removing paddings please help 

This pop up occurs everytime i send PR and after pull then also it remain same please help

**Comment by parasss19** [comment]
> * git pull
> * git push origin [branch name]
> 
> If you want you can create a fresh PR


Hi @priyankarpal 
Now its up to date . Can you review it I removed the extra paddings

**Comment by priyankarpal** [comment]
> > * git pull
> > * git push origin [branch name]
> > 
> > If you want you can create a fresh PR
> 
> Hi @priyankarpal Now its up to date . Can you review it I removed the extra paddings
> 
> 

let me check

**Comment by parasss19** [comment]
# When i delopy on my system

**Comment by priyankarpal** [comment]
yeah just do these & after that push code
## suggestion
- `git remote add upstream https://github.com/priyankarpal/ProjectsHut`
- `git fetch upstream`
- `git merge upstream/[your-branch-name]`

**Comment by parasss19** [comment]
> 

@priyankarpal 
I have to push in upstream or origin ? Actually its my first time for open source so please guide me

**Comment by priyankarpal** [comment]
> > 
> 
> @priyankarpal I have to push in upstream or origin ? Actually its my first time for open source so please guide me
> 
> 

just push 

`git push origin your-branch-name`

**Comment by parasss19** [comment]
> > > 
> > 
> > 
> > @priyankarpal I have to push in upstream or origin ? Actually its my first time for open source so please guide me
> > 
> 
> just push
> 
> `git push origin your-branch-name`

Done

**Comment by priyankarpal** [comment]
> > * git merge upstream/[your-branch-name]
> 
> Hi @priyankarpal i have one question Like now i have to delete this branch ? And can i work on some other issues now?

in this project, your branch will automatically be deleted after got merged your PR. You can create another branch for another issue

**Pull request merged**
