### PR TITLE
Idata: project addition by [slayerrr12 ] #issue_number 491

### PR DESCRIPTION
**Pull request by slayerrr12**
## Related Issue

**Issue no. : #491**

## Description
adding a unique Discord bot project exclusively assigned to me. This bot will have advanced moderation, entertaining commands, and efficient server meta-data extraction. Some features will be powered by OpenAI's API.

## Screenshots
image

### CODE REVIEW

**Comment by slayerrr12** [comment]
why has my deployment failed??

**Comment by priyankarpal** [comment]
> why has my deployment failed??

there are some problems with vercel wait I will merge it soon if any changes required I will ping here.

**Comment by slayerrr12** [comment]
the quality check failing because the object is not in proper format ... what can i do to resolve it

**Comment by slayerrr12** [comment]
pls enlighten me a little about the json check .it says that the error is in the syntax of 4 json files

**Comment by priyankarpal** [comment]
> the quality check failing because the object is not in proper format ... what can i do to resolve it

for quality check format files using `pnpm format` 

[warn] .github/ISSUE_TEMPLATE/project-add.yml
[warn] contributing.md
[warn] src/DB/projects.json

**Comment by slayerrr12** [comment]
> > the quality check failing because the object is not in proper format ... what can i do to resolve it
> 
> for quality check format files using `pnpm format`
> 
> [warn] .github/ISSUE_TEMPLATE/project-add.yml [warn] contributing.md [warn] src/DB/projects.json

what i mean where will i have to go to resolve them should i create another pr or what???

**Comment by priyankarpal** [comment]
> > > the quality check failing because the object is not in proper format ... what can i do to resolve it
> > 
> > 
> > for quality check format files using `pnpm format`
> > [warn] .github/ISSUE_TEMPLATE/project-add.yml [warn] contributing.md [warn] src/DB/projects.json
> 
> what i mean where will i have to go to resolve them should i create another pr or what???

it will be good if you create new fresh PR also check the docs one more time

**Comment by slayerrr12** [comment]
so what is going to happen to this pr will you close it??

**Comment by priyankarpal** [comment]
> so what is going to happen to this pr will you close it??

you can close this PR

**Comment by slayerrr12** [comment]
alright

**Pull request closed without merging**
