### PR TITLE
feat: optimizing App router implementation for better SEO

### PR DESCRIPTION
**Pull request by s2sharpit**
## Related Issue

Closes: #1906 

## Description
Optimizing app router for better SEO

### CODE REVIEW

**Comment by priyankarpal** [comment]
@s2sharpit I'll check it on my local system shortly, and then I'll provide you with an update.

**Review by priyankarpal — CHANGES_REQUESTED** [review]
we can move `ProjectList.tsx` to `components/projects/`

**Comment by s2sharpit** [comment]
> we can move `ProjectList.tsx` to `components/projects/`

Sure, I have done that. Kindly check it.

**Review by priyankarpal — APPROVED** [review]
superb! 👏🏻 🔥

**Pull request merged**
