### PR TITLE
First Translation Guide #75

### PR DESCRIPTION
**Pull request by Hamthoven**
## Description

A new folder has been created for the translation guide and translations to be saved.
I hope to add Translation guide link to README.md after this branch is successfully merged.

## Screenshots

There is a new folder called `translations`.
image

There is a translation guide inside the folder, and when someone translate documents into a new language, they create a new folder inside it.
image

## Related Issue

https://github.com/priyankarpal/ProjectsHut/issues/75

## Checklist

Please review and check off the following items before submitting your PR:

 

- [x] I have tested my changes to ensure they work as expected
- [x] I have included documentation for any new features or changes
- [ ] I have formatted my code according to the project's style guidelines
- [ ] I have written tests for any new features or changes
- [ ] I have run the project's test suite and verified that all tests pass
- [ ] I have updated the README and any other relevant documentation
- [x] I have checked for any spelling or grammatical errors

## Additional Information

The Korean translation will work with the new branch after this branch has merged for ease of project management.
It will be a sample for others.

### CODE REVIEW

**Review by priyankarpal — APPROVED** [review]

**Review by priyankarpal — APPROVED** [review]
Looks good.

**Comment by Hamthoven** [comment]
I was going to make a new branch after this, but do you think it would be better to proceed here?

**Comment by priyankarpal** [comment]
> Looks good but could you add one language translation?

I think you can do it here.

**Comment by Hamthoven** [comment]
Ok, I push again after I translated. :)

**Comment by Hamthoven** [comment]
I have a question in the last sentence of this part. Please let me know if it is connected to the previous sentence or if there is a separate sentence with more words.

image

**Comment by priyankarpal** [comment]
> I have a question in the last sentence of this part. Please let me know if it is connected to the previous sentence or if there is a separate sentence with more words.
> 
> image

separate

**Comment by Hamthoven** [comment]
The Korean translation has been completed. I created the folder as I wrote in the translation document. After merging, I would like you to add a link to the translation guide document on README.md in the main page.

**Comment by priyankarpal** [comment]
> The Korean translation has been completed. I created the folder as I wrote in the translation document. After merging, I would like you to add a link to the translation guide document on README.md in the main page.

but is there any problem? 
image

**Comment by Hamthoven** [comment]
Oh, I don't know why you have problem. But my devices I tested are fine.   
And the results of 3 files seem I wanted. They are translated.

**Desktop** (OS: Window 10, Root: Chrome, MSEdge)
image
    
    
**Laptop** (OS: MacOS Ventura 13.2, Root: Chrome)
스크린샷 2023-03-13 오전 10 38 58
    
    
**Mobile** (OS: Android 13, Root: GitHub Application)
Screenshot_20230313_103543_GitHub

**Comment by priyankarpal** [comment]
> Oh, I don't know why you have problem. But my devices I tested are fine. And the results of 3 files seem I wanted. They are translated.
> 
> **Desktop** (OS: Window 10, Root: Chrome, MSEdge) image
> 
> **Laptop** (OS: MacOS Ventura 13.2, Root: Chrome) 스크린샷 2023-03-13 오전 10 38 58
> 
> **Mobile** (OS: Android 13, Root: GitHub Application) Screenshot_20230313_103543_GitHub

ok ok I think I'm using Brave so I'm facing this problem.

**Review by priyankarpal — APPROVED** [review]
ok

**Comment by Hamthoven** [comment]
Thank you for chance to contribute ;)

**Pull request merged**
