### PR TITLE
chore: project addition added by Ludo Game

### PR DESCRIPTION
**Pull request by PatilHarshh**
## Related Issue

#1921 

## Description

Game of Ludo

### CODE REVIEW

**Review by priyankarpal — APPROVED** [review]

**Comment by PatilHarshh** [comment]
@priyankarpal label?

**Comment by priyankarpal** [comment]
> @priyankarpal label?

We are not providing any labels for project additions as they are not associated with solving any issues.( according to gssoc23 rules)

**Comment by PatilHarshh** [comment]
@priyankarpal i give me issue to solve ! because 8 days are left

**Comment by priyankarpal** [comment]
> @priyankarpal i give me issue to solve ! because 8 days are left

find problems if need to fix then I will assign

**Pull request merged**
