### PR TITLE
feat: footer redesigned #235

### PR DESCRIPTION
**Pull request by Bharadwajshivam28**
@priyankarpal  issue no #235

### CODE REVIEW

**Comment by Bharadwajshivam28** [comment]
@priyankarpal any changes needed?

**Comment by priyankarpal** [comment]
> @priyankarpal any changes needed?

no

**Review by priyankarpal — APPROVED** [review]
Completed. Thanks for your contributions 🎉 ❤️

**Comment by Bharadwajshivam28** [comment]
> Completed. Thanks for your contributions tada heart

thanks for guiding

**Pull request merged**
