### PR TITLE
5 more languages added 

### PR DESCRIPTION
**Pull request by Abhinavcode13**
#677   issue resolved @priyankarpal kindly merge it. thanks ,<3

### CODE REVIEW

**Comment by Abhinavcode13** [comment]
@priyankarpal please check this

**Comment by priyankarpal** [comment]
could you create a fresh PR?  also, create a different branch. make sure to fetch upstream @Abhinavcode13

**Review by Abhinavcode13 — COMMENTED** [review]
done

**Comment by priyankarpal** [comment]
hey @Abhinavcode13 please create a PR there are lots of files changed also, make sure to fetch upstream

**Pull request closed without merging**
