### PR TITLE
src/components/ProjectList.jsx updated style of tags of tech-stacks

### PR DESCRIPTION
**Pull request by anonymgit**
## Description
- **ISSUE** -idea is to change style of tags of tech-stack

## Screenshots
**In Day Light Mode**
image

**In Dark Mode**
image

### CODE REVIEW

**Comment by anonymgit** [comment]
> change the bg & text color according to the theme color image

I didn't found any documentation regarding theme related to this repo ,So I tried to match the theme color and I think it is matching, can you mention the theme color so that i can make changes according to the theme.

**Comment by priyankarpal** [comment]
add bg a little bit dark & text white

**Comment by anonymgit** [comment]
**Day Light Mode**
image

**Dark Mode**
image

**Comment by priyankarpal** [comment]
we need to fix for mobile view 


image

**Comment by AkanshaMundel** [comment]
@priyankarpal could you assign me I'll fix it according to mobile view

**Comment by priyankarpal** [comment]
> @priyankarpal could you assign me I'll fix it according to mobile view

he is working on this issue

**Comment by AkanshaMundel** [comment]
ok , will work on change required label or it already assign to some else because am not able to find which are open issue

**Comment by priyankarpal** [comment]
> ok , will work on change required label or it already assign to some else because am not able to find which are open issue

check issue labelled as `status: ready for dev` or if you find any bugs want to add feat then you can create

**Pull request merged**
