### PR TITLE
data: project addition by [Niladri2003] #510

### PR DESCRIPTION
**Pull request by Niladri2003**
## Related Issue

Added a project for the issue - data: project addition by Niladri2003 #510 

## Description

This is a simple weather made with JS, HTML ,CSS

### CODE REVIEW

**Comment by priyankarpal** [comment]
this branch has a conflicts error. Please resolve it

**Comment by Niladri2003** [comment]
Yeah , I think the conflict issue is resolved .
Is there any other issue please let me know.

Thank you .

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Comment by priyankarpal** [comment]
there is a formatting issue please fix this issue using `pnpm format`

- `src/DB/projects.json`

**Comment by Niladri2003** [comment]
After running pnpm format some conflicts occured and after fixing those conflicts i get this error 
image

Help me

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Comment by priyankarpal** [comment]
now it's looking good. I'm merging this PR

**Pull request merged**
