### PR TITLE
Discord

### PR DESCRIPTION
**Pull request by Bharadwajshivam28**
I have added Discord Icon with the link of ProjectsHut in the NavBar.. @priyankarpal 

Screenshot from 2023-04-22 22-43-23

issue no #228

### CODE REVIEW

**Comment by priyankarpal** [comment]
just solve the conflicts error. We added a new feature so that's why it's causing. or you can create a fresh one

**Comment by Bharadwajshivam28** [comment]
okay creating a fresh pr

**Comment by priyankarpal** [comment]
> okay creating a fresh pr

one suggestion for you whenever you create a PR/issue try to add a clear title & description

**Comment by Bharadwajshivam28** [comment]
> 

okay

**Pull request closed without merging**
