### PR TITLE
Adding of discord icon

### PR DESCRIPTION
**Pull request by Bharadwajshivam28**
I have added Discord icon in the Navbar with the link of ProjectsHut

### CODE REVIEW

**Comment by Bharadwajshivam28** [comment]
issue no #228

**Comment by Bharadwajshivam28** [comment]
Screenshot from 2023-04-22 23-39-22

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Comment by Bharadwajshivam28** [comment]
thanks

**Comment by Bharadwajshivam28** [comment]
can we give this project a good footer like its looking incomplete without a good responsive footer

**Comment by priyankarpal** [comment]
> can we give this project a good footer like its looking incomplete without a good responsive footer

try to create a separate issue after you can work that

**Comment by Bharadwajshivam28** [comment]
okay

**Pull request merged**
