### PR TITLE
chore: project addition/added js extension

### PR DESCRIPTION
**Pull request by mohitparmar1**
added leads-tracker extension on this project
issue #1316

### CODE REVIEW

**Review by priyankarpal — CHANGES_REQUESTED** [review]
add issue number to the PR description

**Comment by mohitparmar1** [comment]
sorry bro but I made pr without opening the issue

**Comment by priyankarpal** [comment]
> Sorry bro but I made pr without opening the issue

create an issue first after you get assigned, then create a PR. it's the best practice. 

Now create an issue then add to the PR description so that I can merge the PR.

**Comment by mohitparmar1** [comment]
issue #1316 and conflicts resolved!

**Review by priyankarpal — APPROVED** [review]

**Pull request merged**
