### PR TITLE
added new projects

### PR DESCRIPTION
**Pull request by iamharshkr**

### CODE REVIEW

**Comment by priyankarpal** [comment]
please add issue number

**Comment by iamharshkr** [comment]
Add a new project to the list
I want to add a new project to the list

**Comment by priyankarpal** [comment]
> Add a new project to the list I want to add a new project to the list

yes please add the issue number so that I can merge this PR.

**Comment by iamharshkr** [comment]
Add a new project to the list
I want to add a new project to the list

Issue Number #846

**Comment by priyankarpal** [comment]
> Add a new project to the list I want to add a new project to the list
> 
> Issue Number #846

this is the PR number

**Comment by iamharshkr** [comment]
Add a new project to the list
I want to add a new project to the list

Issue Number #847

**Review by priyankarpal — APPROVED** [review]
Thank you for contributing your projects here 👏🏻 🎉

**Pull request merged**
