### PR TITLE
feat: style navbar links on hover and focus

### PR DESCRIPTION
**Pull request by Amitavpanda**
## Description
This pull request adds styling changes to the navlinks to provide better visual feedback to the users when hovering or selecting them.
you can refer the video for the expected behavior.

## Video of the implementation

https://github.com/priyankarpal/ProjectsHut/assets/56599943/232eacb1-6e37-4b4c-8404-5a3c14403f6c

Please review this pull request and let me know if you have any questions or concerns or any further changes I can make.

Thank you for your time!

### CODE REVIEW

**Comment by Amitavpanda** [comment]
@priyankarpal following your instructions, i made a fresh PR for this issue.
Please review this pull request and let me know any changes I can make and this time I completed used pnpm instead of npm.

**Comment by priyankarpal** [comment]
also there are some conflicts please use `git pull` in local & update all branch

**Comment by priyankarpal** [comment]
> > also, there are some conflicts please solve, Make sure to update your all branches
> 
> @priyankarpal Someone else has also made some changes in the same lines of code I made, that's why its showing conflicts, what to do now

ok let me check

**Comment by priyankarpal** [comment]
ig now it's fine @Amitavpanda for desktop view.

**Comment by Amitavpanda** [comment]
should  I make some other changes

**Comment by priyankarpal** [comment]
> > should I make some other changes
> 
> The sidebar is not working could you check?

fixed done.

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Comment by Amitavpanda** [comment]
@priyankarpal Thank you for merging my pull request! I'm glad you like the changes.

**Pull request merged**
