### PR TITLE
chore: Added IT Service Web-App

### PR DESCRIPTION
**Pull request by SyedImtiyaz-1**
## Issue No. #1366 
Hello @priyankarpal ,
## Description-
It is a IT Solution website for the Students which are in the final year and those who need projects. 👍🏻 

## Screenshots -
Screenshot from 2023-06-25 00-38-46

## Checklist for projects addition 
 
- [x] My project has contribution guidelines.
- [x] My project has a Code of Conduct.
- [x] My project has a README file.
- [x] My project has a License.

---

### CODE REVIEW

**Review by priyankarpal — CHANGES_REQUESTED** [review]
it is essential that your projects include a contributing guide, code of conduct, license, and a readme. These requirements must be fulfilled without any exceptions.

**Comment by SyedImtiyaz-1** [comment]
> it is essential that your projects include a contributing guide, code of conduct, license, and a readme. These requirements must be fulfilled without any exceptions.

But this time I have followed the rules and just added the project under the rules and regulations.
If you think this is wrong then please tell me.

**Comment by priyankarpal** [comment]
> > it is essential that your projects include a contributing guide, code of conduct, license, and a readme. These requirements must be fulfilled without any exceptions.
> 
> But this time I have followed the rules and just added the project under the rules and regulations. If you think this is wrong then please tell me.

in your project you need to add contributing guide, license, readme, code of conduct after I can merge the PR

**Comment by SyedImtiyaz-1** [comment]
Like this  : 
Screenshot from 2023-06-25 02-20-26


> > > it is essential that your projects include a contributing guide, code of conduct, license, and a readme. These requirements must be fulfilled without any exceptions.
> > 
> > 
> > But this time I have followed the rules and just added the project under the rules and regulations. If you think this is wrong then please tell me.
> 
> in your project you need to add contributing guide, license, readme, code of conduct after I can merge the PR

**Comment by priyankarpal** [comment]
> Like this ? : Screenshot from 2023-06-25 02-20-26
> 
> > > > it is essential that your projects include a contributing guide, code of conduct, license, and a readme. These requirements must be fulfilled without any exceptions.
> > > 
> > > 
> > > But this time I have followed the rules and just added the project under the rules and regulations. If you think this is wrong then please tell me.
> > 
> > 
> > in your project you need to add contributing guide, license, readme, code of conduct after I can merge the PR

yeah also, make sure to add  Code of conduct & contributing guide

**Comment by SyedImtiyaz-1** [comment]
Hello @priyankarpal ,

## Screenshot -
image

Now it is ready to `merge` 👍🏻

**Review by priyankarpal — APPROVED** [review]

**Pull request merged**
