### PR TITLE
chore: project addition by sumitkr2000 #1395

### PR DESCRIPTION
**Pull request by sumitkr2000**
## Related Issue

#1395 

## Description

Hey @priyankarpal I have added the shades project to your repo. Please review my pr and merge it.

## Screenshots

image

## Checklist for projects addition 
 
- [ ] My project has contribution guidelines.
- [ ] My project has a Code of Conduct.
- [ ] My project has a README file.
- [ ] My project has a License.

---

Please note that if your project doesn't meet these requirements, your PR may be closed. Make sure to include these elements in your project before submitting the PR.

### CODE REVIEW

**Review by priyankarpal — CHANGES_REQUESTED** [review]
In order to merge the pull request, it is essential that your projects include a valid contributing guide, code of conduct, license, and a readme. These requirements must be fulfilled without any exceptions.

**Comment by sumitkr2000** [comment]
Okay give to some time to make this changes

**Comment by priyankarpal** [comment]
this branch has a conflicts error. Please resolve it

**Comment by priyankarpal** [comment]
> this branch has a conflicts error. Please resolve it

solved

**Review by priyankarpal — APPROVED** [review]

**Comment by sumitkr2000** [comment]
thank you @priyankarpal I am actually traveling outside so quite busy.

**Comment by sumitkr2000** [comment]
hey @priyankarpal why did you remove the labels???

**Comment by priyankarpal** [comment]
> hey @priyankarpal why did you remove the labels???

We are not providing any labels for project additions as they are not associated with solving any issues according to gssoc23 rules

**Comment by sumitkr2000** [comment]
okay!!!

**Pull request merged**
