### PR TITLE
Fix issue 504

### PR DESCRIPTION
**Pull request by ritik48**
## Related Issue

#504 

## Description

Removed mt-4 from the p tag in footer and this fixed alignment issue in footer.

## Screenshots
projecthut commit preview 1
projecthut commit preview 2

### CODE REVIEW

**Comment by priyankarpal** [comment]
add `Under MIT Lincence` center for mobile & desktop view

**Comment by priyankarpal** [comment]
> @priyankarpal like this ? projecthut ceter

I mean above the copyright

**Comment by priyankarpal** [comment]
> @priyankarpal is it good now ?

share ss

**Comment by ritik48** [comment]
@priyankarpal 
ph1
ph2

**Comment by ritik48** [comment]
@priyankarpal Thanks , its was my first contribution. You helped a lot.

**Pull request merged**
