### PR TITLE
feat(fix issue 1171): copy snippet

### PR DESCRIPTION
**Pull request by vaibhav-xt**
## Related Issue
    Issue No. #1171

- [X] I am a GSSOC contributor.

   On clicking code will copy
## Description
    On clicking code will be copy

## Screenshots
https://github.com/vaibhav-xt/ProjectsHut/assets/90946899/bfcef7bc-0fed-4115-9819-8e37ff4c44eb

### CODE REVIEW

**Comment by priyankarpal** [comment]
I will check it soon. @vaibhav-xt

**Comment by priyankarpal** [comment]
could you add copy button for this also? 
image

**Comment by vaibhav-xt** [comment]
Definitely, I think I forgot about that.

**Comment by vaibhav-xt** [comment]
Hey, I added this to all the code snippets. You are good to merge.
Screenshot (58)

**Comment by priyankarpal** [comment]
hey @vaibhav-xt but I'm not seeing any changes 
image

**Comment by vaibhav-xt** [comment]
Sorry, having some problems that's why it was not committed but I added that for all snippets on the first day.

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Pull request merged**
