### PR TITLE
Project Addition: Added Google Keep Clone Project

### PR DESCRIPTION
**Pull request by abhinav-m22**
## Related Issue

* Project for issue - #476 

## Description
An updated version of Google Keep Clone with updated UI and UX. It can add, remove and archive notes and is styled using MaterialUI, CSS and JSX.

## Features:
1. Users can keep a track of their daily tasks via adding the notes.
2. The notes can be archived(hidden).
3. Users can delete the notes.
4. The deleted and archived notes will be visible under different sections and they can also be restored.
5. Option to delete the notes permanently is also available.

## Screenshots

image

image

### CODE REVIEW

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Comment by abhinav-m22** [comment]
Hey @priyankarpal ..
Thank you for accepting the contribution.
Can you please add the GSSoC'23 label for this PR?

**Comment by abhinav-m22** [comment]
Hey @priyankarpal  ..
Thank you for accepting the contribution.
Please add the GSSoC'23 label for this PR.

**Comment by priyankarpal** [comment]
> Hey @priyankarpal .. Thank you for accepting the contribution. Please add the GSSoC'23 label for this PR.

done

**Pull request merged**
