### PR TITLE
Added toggle switch to the navbar for light/dark mode

### PR DESCRIPTION
**Pull request by karthiknadar1204**
#376 

## Description
Replaced the emoji for dark light mode with a toggle switch for better yser engagement

## Screenshots

Screenshot 2023-05-22 at 3 49 59 PM

Screenshot 2023-05-22 at 3 50 04 PM

### CODE REVIEW

**Comment by priyankarpal** [comment]
@karthiknadar1204 you've created wrong PR 

image

**Comment by karthiknadar1204** [comment]
How so, i removed all the changes on the navbar and created one with the new changes
Could you help me with how to correct it

**Comment by priyankarpal** [comment]
> How so, i removed all the changes on the navbar and created one with the new changes Could you help me with how to correct it

I guess you haven't pushed new branch

**Comment by karthiknadar1204** [comment]
Will revert back at 5:45pm,is that fine?

**Comment by karthiknadar1204** [comment]
@priyankarpal I tried following the steps in the readme to push the new changes, what commands do i use to push these new changes like how to push the new branch and how to move from there

**Comment by priyankarpal** [comment]
> @priyankarpal I tried following the steps in the readme to push the new changes, what commands do i use to push these new changes like how to push the new branch and how to move from there

push here using `git push origin branch_name`

**Comment by karthiknadar1204** [comment]
Screenshot 2023-05-22 at 5 31 03 PM
Screenshot 2023-05-22 at 5 31 25 PM

Look these are the steps i followed whie making the present pr

 git push origin branch_name. ->here branch name would mean fix-issue-376, is that right,but i did the same thing here in this pr earlier as well

**Comment by karthiknadar1204** [comment]
Could you share the steps to do so @priyankarpal to update the branch

**Comment by priyankarpal** [comment]
> Could you share the steps to do so @priyankarpal to update the branch

what if we schedule a meet?

**Comment by karthiknadar1204** [comment]
should do, when is a good time for you

**Comment by priyankarpal** [comment]
> should do, when is a good time for you

I'm available now. you can msg me on twitter

**Comment by priyankarpal** [comment]
> I am already following you apparently,message failed to send is what it is showing https://twitter.com/Karthikreincar1
> 
> my twitter handle,probably we have to be following each other

ok

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Pull request merged**
