### PR TITLE
chore: project added weather report

### PR DESCRIPTION
**Pull request by prachisingh1008**
## Related Issue
#1490 

## Description
This project will five information about current weather condition of the location entered by user along with map of that location

## Checklist for projects addition

 

- [x] My project has contribution guidelines.
- [x] My project has a Code of Conduct.
- [x
Screenshot (370)
] My project has a README file.
- [ ] My project has a License.

---

Please note that if your project doesn't meet these requirements, your PR may be closed. Make sure to include these elements in your project before submitting the PR.

### CODE REVIEW

**Comment by prachisingh1008** [comment]
please review my request

**Review by priyankarpal — CHANGES_REQUESTED** [review]
Please follow our contributing guidelines. This is an invalid PR. You've added a whole code here that we don't collect. we collect data only json format.

**Comment by prachisingh1008** [comment]
please review my pr request

**Comment by priyankarpal** [comment]
ig you've created another 2 PRs so close unnecessary PRs

**Pull request closed without merging**
