### PR TITLE
fix: resolve issue2125

### PR DESCRIPTION
**Pull request by Monilprajapati**
## Related Issue : Issue2125
Filter clear button Issue 

## Description

Fiter clear button was visible whether there is any filter selected or not.

### CODE REVIEW

**Comment by priyankarpal** [comment]
@Monilprajapati will check soon

**Comment by Monilprajapati** [comment]
> @Monilprajapati will check soon. Is it your other account? https://github.com/maxpratz

Yeahhh I created for an event purpose which i am going to conduct in the next week in my college. Is there any problem?

**Comment by Monilprajapati** [comment]
> > @Monilprajapati will check soon. Is it your other account? https://github.com/maxpratz
> 
> Yeahhh I created for an event purpose which i am going to conduct in the next week in my college. Is there any problem?

Ohhh I see the PR has made from that account let me do something

**Comment by priyankarpal** [comment]
> > > @Monilprajapati will check soon. Is it your other account? https://github.com/maxpratz
> > 
> > 
> > Yeahhh I created for an event purpose which i am going to conduct in the next week in my college. Is there any problem?
> 
> Ohhh I see the PR has made from that account What do i need to do now?

whenever you contribute please try to use a single account it will help to verify the person

**Comment by Monilprajapati** [comment]
> > > > @Monilprajapati will check soon. Is it your other account? https://github.com/maxpratz
> > > 
> > > 
> > > Yeahhh I created for an event purpose which i am going to conduct in the next week in my college. Is there any problem?
> > 
> > 
> > Ohhh I see the PR has made from that account What do i need to do now?
> 
> whenever you contribute please try to use a single account it will help to verify the person

Okkk Will take care from next time Thank you is there any futher steps to follow?

**Comment by priyankarpal** [comment]
> > > > > @Monilprajapati will check soon. Is it your other account? https://github.com/maxpratz
> > > > 
> > > > 
> > > > Yeahhh I created for an event purpose which i am going to conduct in the next week in my college. Is there any problem?
> > > 
> > > 
> > > Ohhh I see the PR has made from that account What do i need to do now?
> > 
> > 
> > whenever you contribute please try to use a single account it will help to verify the person
> 
> Okkk Will take care from next time Thank you is there any futher steps to follow?

you can check the website for best practices https://opensource.creativecommons.org/

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Pull request merged**
