### PR TITLE
New Project Added

### PR DESCRIPTION
**Pull request by ozanbatuhankurucu**
## Description

I just added a new Project.

## Checklist

Please review and check off the following items before submitting your PR:

 

- [x] I have tested my changes to ensure they work as expected
- [x] I have included documentation for any new features or changes
- [x] I have formatted my code according to the project's style guidelines
- [x] I have written tests for any new features or changes
- [ ] I have run the project's test suite and verified that all tests pass
- [ ] I have updated the README and any other relevant documentation
- [x] I have checked for any spelling or grammatical errors

### CODE REVIEW

**Comment by ozanbatuhankurucu** [comment]
As a suggestion, we can add a preview link about the related project on the cards. What do you think? @priyankarpal

**Comment by ozanbatuhankurucu** [comment]
Screenshot 2023-04-01 at 11 56 52

Like in this screenshot, the icons are github link and preview link related to the project. @priyankarpal

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Comment by priyankarpal** [comment]
> As a suggestion, we can add a preview link about the related project on the cards. What do you think? @priyankarpal

yeah sure we can add these features. Just need to add a new card design. In that card, if we add extra code. It will look boring.

**Pull request merged**
