### PR TITLE
Splash Screen Added

### PR DESCRIPTION
**Pull request by Saurav-Pant**
(https://user-images.githubusercontent.com/103263909/232105517-649cc1c0-4b65-49be-b017-9c0586914a72.png)

### CODE REVIEW

**Comment by priyankarpal** [comment]
try to rename to `SplashScreen.jsx`

**Comment by priyankarpal** [comment]
could you fix this problem?

https://user-images.githubusercontent.com/88102392/232106275-4d963e18-5d2c-4888-af3b-5dd5d08830f0.mp4

**Comment by Saurav-Pant** [comment]
> try to rename to `SplashScreen.jsx`

Renamed

**Comment by Saurav-Pant** [comment]
> could you fix this problem?

@priyankarpal Here I can't properly understand what's the problem.

**Comment by Saurav-Pant** [comment]
> could you fix this problem?

I will try @priyankarpal

**Comment by Saurav-Pant** [comment]
is footer is ok to show, when SplashScreen working? @priyankarpal

**Comment by priyankarpal** [comment]
> is footer is ok to show, when SplashScreen working? @priyankarpal

just show only splash screen page

**Comment by Saurav-Pant** [comment]
@priyankarpal can you give me any rough idea of how I do this, bcoz we have a footer and navbar in a different component?

**Comment by priyankarpal** [comment]
Import your splash screen component into the main app component.

**Comment by Saurav-Pant** [comment]
I have made this but I don't know why I am not able to push this code to Github.
https://user-images.githubusercontent.com/103263909/232314778-c3503a1b-72d7-45c1-b17a-b16595829aa0.mp4

**Comment by priyankarpal** [comment]
ok then try to create new PR

**Pull request closed without merging**
