### PR TITLE
Project Addition: Added a new Project

### PR DESCRIPTION
**Pull request by abhinav-m22**
## Related Issue

* Added a project for the issue - #558

### CODE REVIEW

**Comment by abhinav-m22** [comment]
Hey @priyankarpal ..
I've created  a new PR - #652 
Please check it.

**Comment by priyankarpal** [comment]
this branch has a conflicts error. Please resolve it

**Comment by abhinav-m22** [comment]
The new PR which I have created has no conflicts.  
Please have a look - #652 
I will close this PR once the new one is merged.

**Comment by priyankarpal** [comment]
ok, so I'm closing this one. New one will merge soon

**Pull request closed without merging**
