### PR TITLE
chore: project addition by [anshulsoni4] #1757

### PR DESCRIPTION
**Pull request by anshulsoni4**
## Related Issue
This PR closes issue no. #1757 (project addition by anshul soni)

## Description
added music player webpage which is just like spotify where you can play your songs

## Screenshots
image

### CODE REVIEW

**Comment by anshulsoni4** [comment]
please review

**Review by anshulsoni4 — COMMENTED** [review]
updated

**Review by anshulsoni4 — COMMENTED** [review]
done

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Pull request merged**
