### PR TITLE
Fix issue #684 Bug in project.json file

### PR DESCRIPTION
**Pull request by KawishAli6578**
## Related Issue

fix issue number #684 

fix json file as the teck key value was not correct (due to which some project was not showing when doing sorting) and also updated contribute.md file so people can follow same naming convention when writing their tech name
 
as you can see localhost project 

image

and deploy project their is change in number of project 

image

and same goes for other tech

### CODE REVIEW

**Comment by priyankarpal** [comment]
run `pnpm format` to fix formatting issue

**Comment by KawishAli6578** [comment]
do i need to run it on my code locallay and then again create a pull request as i did run it before creating pr

**Comment by priyankarpal** [comment]
> do i need to run it on my code locallay and then again create a pull request as i did run it before creating pr

have you created PR directly from github?

**Comment by KawishAli6578** [comment]
yes

**Comment by priyankarpal** [comment]
> yes

then don't need to run in locally I'm merging

**Comment by KawishAli6578** [comment]
okay good

**Comment by KawishAli6578** [comment]
can you tell difference between pr directly from github and from vs code iguess?

**Comment by priyankarpal** [comment]
> can you tell difference between pr directly from github and from vs code i guess?

simple you solved a problem & created PR directly from github & you used GUI for vs code: you cloned it in your local system, fixed problems & pushed your code using CLI

**Pull request merged**
