### PR TITLE
Nav active for mobile devices fix

### LINKED ISSUE #917: Pagination numbering issue and inactive side navigation links on mobile
### Pagination numbering

The pagination on the project list page should display numbers as 1, 2, 3...10 instead of 1, 2, 3, 4, 5, 6, 7, 8, 9, 10. This will provide better clarity on the total number of pages available.

image

### Inactive side navigation links on mobile

On the mobile version of our website, the side navigation links are not active when clicked. This prevents users from accessing the corresponding sections of the page.
image

### Steps color in dark mode on the documentation page

Currently, in dark mode on the documentation page, the color of the steps is not consistent with the overall theme. To improve the visual experience, the steps should have a light purple color when viewed in dark mode.

image

### PR DESCRIPTION
**Pull request by manaver**
This pull request fixes #917 adds the Nav Active feature for mobile devices to enhance the user experience. The Nav Active feature ensures that the active menu item is visually highlighted when accessed on mobile devices, providing better navigation and usability.

### CODE REVIEW

**Comment by priyankarpal** [comment]
why is it failing?

**Comment by manaver** [comment]
> why is it failing?

Idk. In my local machine it is working but not working in codespace and i try everything to commit from local machine but it is not committing. But it is committing from codespace? 😔

**Comment by priyankarpal** [comment]
> > why is it failing?
> 
> Idk. In my local machine it is working but not working in codespace and i try everything to commit from local machine but it is not committing. But it is committing from codespace? pensive

could you share a screenshot?

**Comment by manaver** [comment]
@priyankarpal ok

**Comment by manaver** [comment]
> > > why is it failing?
> > 
> > 
> > Idk. In my local machine it is working but not working in codespace and i try everything to commit from local machine but it is not committing. But it is committing from codespace? pensive
> 
> could you share a screenshot?

I'll close this pull request and try to make a pull request with local machine

**Pull request closed without merging**
