### PR TITLE
Fixed issue-#323

### PR DESCRIPTION
**Pull request by gkprasanth**
#323 

## Description

Fixed issue number #323. Added a dropdown menu that can translate website into other integrated languages. All the translations of texts are present inside public/locale folder where each and every language has it's own folder with a json file containing translations

## Screenshots

image
image
image
image
image
image
image

### CODE REVIEW

**Comment by priyankarpal** [comment]
- This branch has a conflicts error. Please resolve these.

- also, add the button to the right side after the toggle button

**Comment by gkprasanth** [comment]
> * This branch has a conflicts error. Please resolve these.
> * also, add the button to the right side after the toggle button

Yup I will work on them.

**Comment by gkprasanth** [comment]
> * This branch has a conflicts error. Please resolve these.
> * also, add the button to the right side after the toggle button

I have resolved the conflicts can you verify them?

**Comment by priyankarpal** [comment]
create a new fresh PR some code got deleted @gkprasanth you can close this PR

**Pull request closed without merging**
