### PR TITLE
fix: #1044

### PR DESCRIPTION
**Pull request by aditya-stoic-sharma**
## Related Issue
issue: #1044 

## Screenshots
project hub original

after

image

### CODE REVIEW

**Review by priyankarpal — CHANGES_REQUESTED** [review]
could you fix this issue? 

[Screencast from 2023-06-05 23-36-07.webm](https://github.com/priyankarpal/ProjectsHut/assets/88102392/5c6c5f2e-2fc7-4447-a12b-4573a30f170d)

**Comment by aditya-stoic-sharma** [comment]
@priyankarpal can you please specify what exactly is the issue

**Comment by priyankarpal** [comment]
> @priyankarpal can you please specify what exactly is the issue

please check the hover effect & the button problem

**Comment by aditya-stoic-sharma** [comment]
is it good
https://github.com/priyankarpal/ProjectsHut/assets/109134266/b94ee378-67d9-4224-abad-61a10e604181

**Comment by priyankarpal** [comment]
> is it good https://github.com/priyankarpal/ProjectsHut/assets/109134266/b94ee378-67d9-4224-abad-61a10e604181

looks good

**Comment by aditya-stoic-sharma** [comment]
@priyankarpal make the required changes

**Review by priyankarpal — APPROVED** [review]

**Pull request merged**
