### PR TITLE
fix: dispaly command in vs code format

### PR DESCRIPTION
**Pull request by noobtuber20103152**
issue no #830 
please check @priyankarpal

### CODE REVIEW

**Comment by priyankarpal** [comment]
why is it failing?

**Comment by noobtuber20103152** [comment]
PR Title Checker what does it mean? 🧐🧐

**Comment by priyankarpal** [comment]
> PR Title Checker what does it mean? monocle_facemonocle_face

rename title to `fix: your issue name`

**Comment by priyankarpal** [comment]
have you added `upstream` command?

**Comment by noobtuber20103152** [comment]
Yes

**Comment by priyankarpal** [comment]
> Yes

ok so we optimized whole code so please create new PR 😢

**Comment by noobtuber20103152** [comment]
Ok 👌

**Review by priyankarpal — CHANGES_REQUESTED** [review]
you can close this PR

**Pull request closed without merging**
