### PR TITLE
Refactor: Use loader to fetch contributors data.

### LINKED ISSUE #745: [Feat]: Refactor ContributorsCard component
### What feature?

We can refactor the contributors card component to use loader for fetching data instead of useEFfect.

### Add screenshots

Add screenshots

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by kailashchoudhary11**
fixes #745

### CODE REVIEW

**Comment by kailashchoudhary11** [comment]
Ye to major refactor lag rha tha Sir 🥹😭

**Comment by kailashchoudhary11** [comment]
@priyankarpal I've resolved it. Please Review.

**Review by priyankarpal — CHANGES_REQUESTED** [review]

**Comment by kailashchoudhary11** [comment]
Increased @priyankarpal

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Comment by kailashchoudhary11** [comment]
> Looks Good 🎉

By the way I think, We can fetch only 100 contributors at max using this endpoint? Because it is still fetching only 100 contributors.

**Pull request merged**
